### ISSUE TITLE
KeyError in _get_rememberer()

### ISSUE THREAD

**Issue by patrickbr** [IdentityPython/pysaml2#141]
While trying to use pysaml2 in a pyramid application together with repoze.who and pyramid_whoauth, I ran into some unexpected problems. I am creating a WhoAuthenticationPolicy like this:

```
api_factory = make_api_factory_with_config(global_config, "who.ini")
authn_policy = auth.WhoAuthenticationPolicy(api_factory)
config = Configurator(settings=settings, session_factory=session_factory, root_factory='wkp.Root')
config.include("pyramid_whoauth")
config.set_authentication_policy(authn_policy)
```

However, as soon as I am trying to request a view with access restrictions, pysaml2 fails fetching the key 'repoze.who.plugins' from the environ dict. This key is indeed nonexistent. The KeyError happens in self._get_rememberer(environ).

I am strongly suspecting some compatibility problems between the current version of repoze.who and pysaml2 1.0. Is there any way to get pysaml2 to work with pyramid_who or pyramid_whoauth? If not, what is the preferred way to use pysaml2 with pyramid?

Thanks!

**Comment by pcrownov** [comment]
@patrickbr Can you provide more information on your setup for pysaml2 & pyramid_who? I am having the same issue and have been banging my head against the wall for a while on it looking for a fix.

**Comment by patrickbr** [comment]
@pcrownov at @geops, we are using pysaml2 together with repoze.who. We dont use pyramid_who because of some issues we couldn't resolve (I don't remember them all exactly). What we did was to create our own AuthenticationPolicy which communicates with the repoze.who-plugin version of pysaml2. One of main things we have to do there (as mentioned above) is setting request.environ['repoze.who.plugins'] = api.name_registry (api is the repoze.who API). The complete setup was quite painful and took us about a week, but we are using pysaml2 quite stable now for almost 10 months.

**Comment by pcrownov** [comment]
@patrickbr That's awesome thanks! I ended up getting the two working together (kinda), but two of the issues I am having are; it's not storing the user in the headers and it sometimes cycles about 6 saml requests stating they are unsolicited responses before finally accepting one. Do these issues sound familiar to what you ran into using pyramid_who? In either case, would you be willing to share your code for the AuthenticationPolicy you ended up using?
