### ISSUE TITLE
Usage of asserts for validation of SAML tokens

### ISSUE THREAD

**Issue by livenson** [IdentityPython/pysaml2#233]
Hello,

I've noticed that pysaml2 relies a lot in validation on the usage of 'assert' keyword. However, it's removed from the code if compiled with optimisation leaving a very easy way to shoot yourself in the leg by using a library packaged e.g. into RPMs (it's popular to compile with optimisation there).

I wonder, is it a consciousness choice or a bug?

**Comment by rohe** [comment]
> 22 jun 2015 kl. 19:39 skrev Ilja Livenson <notifications@github.com>:
> 
> 
> I've noticed that pysaml2 relies a lot in validation on the usage of 'assert' keyword. However, it’s removed from the code if compiled with optimisation leaving a very easy way to shoot yourself in the leg by using a library packaged e.g. into RPMs (it's popular to compile with optimisation there).

That’s interesting didn’t know that.

> I wonder, is it a consciousness choice or a bug?

Uninformed choice ? :-/

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by peppelinux** [comment]
Time passed, code changed and I'm Happy to close this issue
