### ISSUE TITLE
Not compatible with Tornado or other asyncio based frameworks

### ISSUE THREAD

**Issue by rskumar** [IdentityPython/pysaml2#235]
Since http client used all over this project is urllib, it will block IOLoop until response recieved if used in Tornado or AsyncIO based application.
Any workaround or plan to support such platform. 
One flexible solution seems to expose an api to configure the custom HTTP client provider (tornado.httpclient).

**Comment by rskumar** [comment]
With tornado, the one workaround would be to use Executor (ThreadPoolExecutor), so the SAML authentication can be performed in different thread. But this will always be a workaround, since xml parsing, signing, http-request and validations would take considerable CPU and will affect main IOLoop thread performance.

**Comment by spaceone** [comment]
I would also like to see a solution for asynchronous frameworks (in my case not tornado).

**Comment by rohe** [comment]
I don't know enough about asynchronous frameworks to do this myself apart from the fact that I probably don't have the time. But if someone knowledgable in such frameworks want to have a go at building something I'll definitely give all the support I can to such an endeavor.

**Comment by nixphix** [comment]
Is there any better way to implement SAML for tornado (Jupyterhub), let me know if there is any pointers I willl give it a try and probably contribute.

**Comment by peppelinux** [comment]
urllib and other sock libraries can be Monkey patched. The web Will Be asyncronous, we know, so se could renew these kind of issues asap as there Will be a release in that direction. Asyncio would be the First choice for this
