### ISSUE TITLE
Saml2Client.apply_binding() should return HTTP status code

### ISSUE THREAD

**Issue by spaceone** [IdentityPython/pysaml2#242]
saml2.client.Saml2Client.apply_binding() should return a item 'status' in the returned dict. The status should be the HTTP status code which should be used in the response.

**Comment by spaceone** [comment]
Btw. the examples are mixing 302 and 303. They are using 302 for ACS+HTTP-Artifact, 303 for ACS+HTTP-Redirect and 302 for SLO+HTTP-Redirect.
Is this the wanted behavior? simplesamlphp does:

status = 303 if request.protocol >= (1, 1) and request.method == 'POST' else 302

This seems more correct as 303 forces the next request to be GET while 302 doesn't. (https://tools.ietf.org/html/rfc7231#section-6.4.3)
Does the SAML specs tell something about this?

**Comment by rohe** [comment]
> 7 okt 2015 kl. 08:37 skrev spaceone <notifications@github.com>:
> 
> Btw. the examples are mixing 302 and 303. They are using 302 for ACS+HTTP-Artifact, 303 for ACS+HTTP-Redirect and 302 for SLO+HTTP-Redirect.
> Is this the wanted behavior? simplesamlphp does:
> 
> status = 303 if request.protocol >= (1, 1) and request.method == 'POST' else 302
> 
> This seems more correct as 303 forces the next request to be GET while 302 doesn’t. (https://tools.ietf.org/html/rfc7231#section-6.4.3)

Sounds reasonable. Will apply!

> Does the SAML specs tell something about this?

No, nothing!
Which is what I would have expected.

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett

**Comment by peppelinux** [comment]
@spaceone can you confirm that's the sane otlr It have been changed something in the next releases. A lot of time Is passed!

**Comment by peppelinux** [comment]
I've just checked it, actually .apply_binding returns a dictionary.
https://github.com/peppelinux/Django-Identity/blob/36cf34a3d7f1e10edf7414c350f5025a599e5b8f/djangosaml2_sp/djangosaml2_sp/djangosaml2_spid/views.py#L179

I think that's good enough that this method should not embed the http request in it but just build all the definition to do the conseguent http request.

I hope this approach is widely shared and that you approve of it. Thanks for the support

**Comment by spaceone** [comment]
`.apply_binding` still returns a dictionary without containing the `status` key (except for artifact binding).

**Comment by peppelinux** [comment]
> `.apply_binding` still returns a dictionary without containing the `status` key (except for artifact binding).

Ok, my fault.
I didn't have a test vedo for this so I would have to dig in pysaml2 unit tests or get an example configuration from you.

**Comment by peppelinux** [comment]
I read
https://github.com/peppelinux/Django-Identity/blob/36cf34a3d7f1e10edf7414c350f5025a599e5b8f/djangosaml2_sp/djangosaml2_sp/djangosaml2_spid/views.py#L179

And as you can see I Always handle the sane status code (302) there. So this issue would be good also for a future refactor of my approach

**Comment by spaceone** [comment]
This bug is not about the artifact binding. The artifact binding already does the wanted behavior. the POST and GET binding don't do the correct behavior.

**Comment by spaceone** [comment]
Your django implementation looks wrong, too. It doesn't evaluate HTTP headers and status code set in the return of `apply_binding` (or this is only used for cases which don't do any redirections).

**Comment by spaceone** [comment]
Patch draft:
```
diff --git a/src/saml2/entity.py b/src/saml2/entity.py
index 91219d72..afdb8e4c 100644
--- a/src/saml2/entity.py
+++ b/src/saml2/entity.py
@@ -241,7 +241,7 @@ class Entity(HTTPBase):
             if response:
                 info = self.use_http_artifact(msg_str, destination, relay_state)
                 info["method"] = "GET"
-                info["status"] = 302
+                info["status"] = 302  # TODO: should be 303 on > HTTP/1.0
             else:
                 info = self.use_http_artifact(msg_str, destination, relay_state)
         else:
diff --git a/src/saml2/pack.py b/src/saml2/pack.py
index 5a2534c2..1979e1d8 100644
--- a/src/saml2/pack.py
+++ b/src/saml2/pack.py
@@ -137,7 +137,7 @@ def http_post_message(message, relay_state="", typ="SAMLRequest", **kwargs):
         part["RelayState"] = relay_state
 
     return {"headers": [("Content-type", 'application/x-www-form-urlencoded')],
-            "data": urlencode(part)}
+            "data": urlencode(part), "status": 200}
 
 
 def http_redirect_message(message, location, relay_state="", typ="SAMLRequest",
@@ -194,7 +194,7 @@ def http_redirect_message(message, location, relay_state="", typ="SAMLRequest",
     headers = [('Location', str(login_url))]
     body = []
 
-    return {"headers": headers, "data": body}
+    return {"headers": headers, "data": body, "status": 302}
 
 
 DUMMY_NAMESPACE = "http://example.org/"
```

My mistake: the POST binding is no HTTP redirection, so 200 is okay there.
