### ISSUE TITLE
remote metadata causes error

### ISSUE THREAD

**Issue by spaceone** [IdentityPython/pysaml2#244]
If I specify `{"metadata": {"remote": "https://localhost/idp.xml"}}` in CONFIG the service provider doesn't get properly set up. Saml2Client().metadata is None.

I get the exception:
    idps = self.sp.metadata.with_descriptor("idpsso")
AttributeError: 'NoneType' object has no attribute 'with_descriptor'

There is no request done to the remote-host to fetch the metadata.

**Comment by josedesoto** [comment]
I had the same issue if don’t  set the certificate. Setting the certificate it works, for example: 

```
    'metadata': {
         "remote": [{
            'url': "URL_TO_THE_SP_METADATA",
            'cert':'pki/mycert.pem')
            }]
        },
```

**Comment by rohe** [comment]
Yes, there is an implicit assumption that if you fetch metadata over the net it has to be
signed. Hence, there is a need to define a certificate.
Should make better error handling!

> 28 jul 2015 kl. 17:03 skrev Jose de Soto <notifications@github.com>:
> 
> I had the same issue if don’t set the certificate. Setting the certificate it works, for example:
> 
>     'metadata': {
>          "remote": [{
>             'url': "URL_TO_THE_SP_METADATA",
>             'cert':'pki/mycert.pem')
>             }]
>         },
> 
> —
> Reply to this email directly or view it on GitHub.
> 

- Roland

”Capitalism is the extraordinary belief that the nastiest of men for the nastiest of motives will somehow work for the benefit of all" - John Maynard Keynes.

**Comment by peppelinux** [comment]
This has been fixed over time. Now I can use remote metadata on both my sp and idp (but do not go in production with that on a idp!)
