### ISSUE TITLE
lack of __version__

### ISSUE THREAD

**Issue by novocaine** [IdentityPython/pysaml2#251]
It would be really helpful if pysaml2 supported the standard **version** variable. I maintain a system that leverages this on most packages in order to maintain a specific set of dependencies.

**Comment by rohe** [comment]
> 2 sep 2015 kl. 14:21 skrev James Salter <notifications@github.com>:
> 
> It would be really helpful if pysaml2 supported the standard version variable. I maintain a system that leverages this on most packages in order to maintain a specific set of dependencies.

OK, will make this happen.

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett

**Comment by c00kiemon5ter** [comment]
The latest changes include a `VERSION` file (plain text). This is bundled with the package distribution and read by the code through the `version.py` module and by the docs in `conf.py`. Version information should be in sync from now on.

The following should work with the latest HEAD:

```py
>> import saml2
>> print(saml2.__version__)
4.5.0
```
