### ISSUE TITLE
AttributeError on metadata string creation

### ISSUE THREAD

**Issue by Aquassaut** [IdentityPython/pysaml2#258]
Hi,

When I try to generate a metadata string with the function [create_metadata_string](https://github.com/rohe/pysaml2/blob/ae9d27e5100f002f55ad6eb2b252a0aa5f16a336/src/saml2/metadata.py#L76), I get the following error:

```
Traceback:
File "/home/ods/.virtualenvs/ODS/lib/python2.7/site-packages/saml2/metadata.py" in create_metadata_string
  97.         valid_instance(desc)
File "/home/ods/.virtualenvs/ODS/lib/python2.7/site-packages/saml2/validate.py" in valid_instance
  360.     if instclass.c_value_type and instance.text:

AttributeError: type object 'tuple' has no attribute 'c_value_type'
```

This suggest that the validation call [here](https://github.com/rohe/pysaml2/blob/ae9d27e5100f002f55ad6eb2b252a0aa5f16a336/src/saml2/metadata.py#L102) did not take into account the modification of output of function [entities_descriptor](https://github.com/rohe/pysaml2/blob/ae9d27e5100f002f55ad6eb2b252a0aa5f16a336/src/saml2/metadata.py#L750) made in [this commit](https://github.com/rohe/pysaml2/commit/0dde360db03f13954a6e31b3ac3f5f435ed65f55).

Thank you for the hard work, I appreciate it.

**Comment by peppelinux** [comment]
I'm sorry there hasn't been any response to this for more than 5 years ...

In any case, I hope that this has been resolved and I would like to wait a few weeks for your reply before closing this issue
