### ISSUE TITLE
change exception for unknown binding

### ISSUE THREAD

**Issue by spaceone** [IdentityPython/pysaml2#276]
If a binding is not known no ValueError should be raised. Instead something like UnknownBinding() exception should be raised.

```
    response = self.sp.parse_authn_request_response(message, binding, self.outstanding_queries)#, allow_unsolicited=True)
  File "/usr/lib/python2.7/dist-packages/saml2/client_base.py", line 573, in parse_authn_request_response
    binding, **kwargs)
  File "/usr/lib/python2.7/dist-packages/saml2/entity.py", line 918, in _parse_response
    xmlstr = self.unravel(xmlstr, binding, response_cls.msgtype)
  File "/usr/lib/python2.7/dist-packages/saml2/entity.py", line 361, in unravel
    raise ValueError("Don't know how to handle '%s'" % binding)
```

**Comment by peppelinux** [comment]
Probably it's something interesting to be discussed more.
@ivan @ioparaskev what do you think about that, it's something belonging to policy...

@spaceone I think that a very good PR would be the right way to manage this and I completely agree with you, that's the correct way, a specific exception

**Comment by peppelinux** [comment]
hey... 5 year passed. That's was instead a very exhaustive issue!

**Comment by ioparaskev** [comment]
@peppelinux this has already been take care of: https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/entity.py#L374
but probably this issue was forgotten so it was not mentioned/closed
So this can be marked as resolved
