### ISSUE TITLE
Logout requests raises KeyError

### ISSUE THREAD

**Issue by spaceone** [IdentityPython/pysaml2#281]
```
Traceback (most recent call last):
    sp.global_logout(user.saml.response.name_id)
  File "/usr/lib/python2.7/dist-packages/saml2/client.py", line 106, in global_logout
    entity_ids = self.users.issuers_of_info(name_id)
  File "/usr/lib/python2.7/dist-packages/saml2/population.py", line 42, in issuers_of_info
    return self.cache.entities(name_id)
  File "/usr/lib/python2.7/dist-packages/saml2/cache.py", line 142, in entities
    return self._db[cni].keys()
KeyError: '1=https%3A//master441.deadlock44.intranet/saml/metadata,2=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Anameid-format%3Atransient,4=_d20734fef743f5fcaeca395507e4d4926bf13f23bd'
```

I don't know what this means and how it happened, currently I can't reproduce it.
This should raise something more meaningful.

**Comment by java8dev** [comment]
is this resolved? if so can you share me the resolution.

**Comment by spaceone** [comment]
@java8dev I don't think it's resolved :/

**Comment by ksshetty** [comment]
Hi folks, I seem to have run into this same issue. Can one of you please confirm if this has been resolved or not?

**Comment by ambsw-technology** [comment]
I've run into the same thing.  Anyone figure out how to resolve it?

**Comment by ambsw-technology** [comment]
OK.  The issue is that the SAML Client caches information at `client.users` (using a `Population` object).  If you don't provide an external cache to the client, a new one is created each time a client is constructed.  This means that the logout call doesn't have access to the login cache and triggers the `KeyError`.  So you really have two options:

 - provide an `identity_cache` to the SAML Client when it's constructed
 - use a singleton SAML Client

**Comment by ambsw-technology** [comment]
See also #646 as the cache interface is (currently) proprietary so it's really not compatible with external cache implementations.

**Comment by peppelinux** [comment]
I think that this would belong to some implementation error with third-party wrappers, not belonging to pysaml2.
I didn't see something similar in djangosaml2 or uniauth or djangosaml2idp, so I think that the implementation on how the cache is used is something critical that have to be faced in child projects.

Going to close to keep order but I can reopen this is any of the partecipant will ask it.
Thank you all, there are all important tips anyway

**Comment by ambsw-technology** [comment]
I don't like an answer that is basically "3rd party must implement this correctly" as it's not required in many cases and not easy to diagnose.

I'd rather see this package error on operations that require an external cache if one isn't provided.  The user can be given the option to provide a trivial in-memory cache, but that active choice should make the technical consequences "obvious" (i.e. that an in-mem cache can't be used on a distributed system).

**Comment by ambsw-technology** [comment]
I did some troubleshooing a while back, but don't know the package all that well.  Would it work to create a `NoCache` object that ignores all `set` calls and errors on all `get` calls?  Or is the `Population` used as a within-session store of info?  If `NoCahce` could be the default, that would minimize the need to make code changes and still error (with an intelligent message like "must provide a valid cache to constructor") any time the `Population` object is actually used.
