### ISSUE TITLE
pysaml2 may have trouble finding the xenc:EncryptedKey node

### ISSUE THREAD

**Issue by erickt** [IdentityPython/pysaml2#303]
It appears that pysaml2 is running into the same problem [python-saml](https://github.com/onelogin/python-saml/issues/61) had, where the key is specified by way of a `ds:RetrievalMethod` node that points outside of the `xenc:EncryptedData` node subtree. They fixed it in https://github.com/onelogin/python-saml/commit/94a43fec4cf0da4f2afaf63ed12eae683fed5e31 by searching the assertion for any references to `ds:RetrievalMethod` and moving it into the `xenc:EncryptedData`. I'm not quite sure where in pysaml2 this is done, but it should be pretty easy to implement once discovered :)

**Comment by c00kiemon5ter** [comment]
Fixed by #530 - The fix by onelogin seems closer to #461. I will reconsider this in the future.
