### ISSUE TITLE
create a NameID, nameid-format:PERSISTENT possible issue

### ISSUE THREAD

**Issue by josedesoto** [IdentityPython/pysaml2#310]
The SP, send a SAML request with the next data:

`<samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" />`

It expects a SAML response as (with no attributes):

```
<ns1:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified"
                        NameQualifier="https://idp.test.com/idp.xml"
                        SPNameQualifier="sp.test.com"
                        >test@test.com</ns1:NameID>
```

When I try to create a response with `create_authn_response` it will create a new NameID, based in the `name_id_policy.format` that the SP side wants us to follow (nameid-format:unspecified). In this case `get_nameid` will generate an ID based in the format, name qualifier and sp name qualifier. So the response is something similar to:

```
<ns1:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified"
                        NameQualifier="https://idp.test.com/idp.xml"
                        SPNameQualifier="sp.test.com"
                        >45jfrkljf843ijf208fji34j8914009ru4930</ns1:NameID>
```

The SP does not recognize 45jfrkljf843ijf208fji34j8914009ru4930, because it expects an EMAIL. In the IDP I can force to use: NAMEID_FORMAT_PERSISTENT (in my case, the user_id = EMAIL) and it works but in this case when  `create_authn_response` try to find the NameID always return an empty list. This is because `def store` overwrite the ident (user_id) key:

```
        self.db[ident] = " ".join(val)
        self.db[name_id.text] = ident

        self.db['test@test.com'] = " ".join(val)
        self.db[''test@test.com''] = 'test@test.com'
```

For this reason always create a new nameid, instead of reuse the one in the database.

Is this expected behaviour? Is there a way to set a custom text for nameid-format:unspecified in NameID?

**Comment by peppelinux** [comment]
Reunification of the accounts (account lining), which takes place in SP's ACS, can be carried out outside the subject id.

Any attribute can contribute to this, it's not mandatory to use the subject id for that.

Specifically in the issue you showing to us, it is necessary (or simply convenient!) to consider that in a balanced federation mechanism, aspects such as the name_id format are always agreed in advance and that it is always advisable for the entities involved to conduct the transaction compatibly with this aspect. In a nutshell they must agree on at least one of the supported formats, otherwise one throws hearts and the other responds diamonds

**Comment by peppelinux** [comment]
@c00kiemon5ter what do to with this issue?

**Comment by bjm88** [comment]
hi @c00kiemon5ter how can we have a passthrough value?  Will nameID value always be encrypted or something?
We set the user_id in 
 name_id = IDP.ident.get_nameid(identity["urn:mace:dir:attribute-def:aRecord:patientId"], name_id_policy, sp_name_qualifier, name_qualifier)
    _resp = IDP.create_authn_response(identity, in_response_to, destination, sp_entity_id, userid=patientId, \
         binding=BINDING_HTTP_POST , name_id=name_id ) #name_id=name_id, , authn=auth_info
    http_args = IDP.apply_binding(binding_out,
                                        "%s" % _resp, destination=destination,relay_state=relay_state, response=True)

But a value of Z4145714 for example will come out as  "9f85851ef443c788a8bf181ed0db4202f92713ad3be41a4ca97771bd38e57fe3"

why?  how to do a straight pass through or is this standard encoding or encryption of the actual value?

 <ns1:Subject>
      <ns1:NameID NameQualifier="" SPNameQualifier="https://mychart-np.atlantichealth.org/MyChartPOC" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">9f85851ef443c788a8bf181ed0db4202f92713ad3be41a4ca97771bd38e57fe3</ns1:NameID>
      <ns1:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <ns1:SubjectConfirmationData NotOnOrAfter="2022-01-06T19:43:00Z" Recipient="https://mychart-np.atlantichealth.org/MyChartPOC/Authentication/Saml/Login"/>
      </ns1:SubjectConfirmation>
    </ns1:Subject>

**Comment by c00kiemon5ter** [comment]
hello everyone,

the `IDP.ident.get_nameid` call takes as the second argument the format of the NameID. When the format is persistent (`urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`) then the generated identifier for the given `user-id` will be stable. This does not mean that it will be same as the `user-id`, but given the same `user-id` and persistent format the same NameID will be returned.

If you want the lib to create a NameID with a value that looks like an email you have to specify the format to be emailAddress (`urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`). Again, this does not mean that the value of the NameID will be an actual email address, but the _format_ will resemble an email address.

If you want to control and specify your own value you can create the NameID object on your own (see https://github.com/IdentityPython/pysaml2/issues/850#issuecomment-1009569241). When you create the NameID object you have the control to form the value as you want. This could be made like an email, the same value as the userid, or anything else.
