### ISSUE TITLE
NAMEID_FORMAT_EMAILADDRESS response with hexdigest

### ISSUE THREAD

**Issue by josedesoto** [IdentityPython/pysaml2#311]
If the SAML Request include a `nameid-format:emailAddress` for example:

```
<samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid format:emailAddress"  />
```

The SAML Response include an `hexdigest@domina.com` for example:

```
<ns1:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" NameQualifier="https://test-proxy.test.com/idp.xml" SPNameQualifier="TestSP"                >e53384d86bdefe6bc586962db7b2ba1c2700207f346de2fdebffe3793ad51baf@test.com</ns1:NameID>
```

Is this expected behaviour? Does It make more sense to send the user email? for example:

```
    def get_nameid(self, userid, nformat, sp_name_qualifier, name_qualifier):
        if nformat == NAMEID_FORMAT_EMAILADDRESS:
            import re
            # If userid is already an email
            if re.match("([^@|\s]+@[^@]+\.[^@|\s]+)", userid):
                _id = userid
             # If userid is not an email, it creates one with the domain parameter in the idp conf
             else:
                if not self.domain:
                    raise SAMLError("Can't issue email nameids, unknown domain")
                _id = "%s@%s" % (userid, self.domain)
        # if nameid persistent it creates pseudo-random values
        elif nformat == NAMEID_FORMAT_PERSISTENT:
            _id = self.create_id(nformat, name_qualifier, sp_name_qualifier)

        nameid = NameID(format=nformat, sp_name_qualifier=sp_name_qualifier,
                        name_qualifier=name_qualifier, text=_id)

        self.store(userid, nameid)
        return nameid
```

**Comment by rohe** [comment]
The reasoning behind the implementation as it is, is about divulging information.

’userid' is a local identifier of a person.
You probably do not want to tell the other side what the local identifier is.
At least I don’t, hence the code is made not to.

> 2 feb 2016 kl. 18:45 skrev Jose de Soto <notifications@github.com>:
> 
> If the SAML Request include a nameid-format:emailAddress for example:
> 
> <samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:11:nameid format:emailAddress"  />
> 
> The SAML Response include an hexdigest@dominacom for example:
> 
> <ns1:NameID Format="urn:oasis:names:tc:SAML:11:nameid-format:emailAddress" NameQualifier="https://test-proxytestcom/idpxml" SPNameQualifier="TestSP"                >e53384d86bdefe6bc586962db7b2ba1c2700207f346de2fdebffe3793ad51baf@testcom</ns1:NameID>
> 
> Is this expected behaviour? Does It make more sense to send the userid? for example:
> 
>     def get_nameid(self, userid, nformat, sp_name_qualifier, name_qualifier):
>         if nformat == NAMEID_FORMAT_EMAILADDRESS:
>             import re
>             if rematch("([^@|\s]+@[^@]+\[^@|\s]+)", userid):
>                 _id = userid
>             else:
>                 if not selfdomain:
>                     raise SAMLError("Can't issue email nameids, unknown domain")
>                 _id = "%s@%s" % (userid, selfdomain)
> 
>         elif nformat == NAMEID_FORMAT_PERSISTENT:
>             _id = selfcreate_id(nformat, name_qualifier, sp_name_qualifier)
> 
>         nameid = NameID(format=nformat, sp_name_qualifier=sp_name_qualifier,
>                         name_qualifier=name_qualifier, text=_id)
> 
>         selfstore(userid, nameid)
>         return nameid
> 
> —
> Reply to this email directly or view it on GitHub.
> 

”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss

**Comment by josedesoto** [comment]
Hi Roland,

But what happens if the third party SP requires that the NameID contain the user email address. Technically:

```
<ns1:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" NameQualifier="https://test-proxy.test.com/idp.xml" SPNameQualifier="TestSP" >
user_name@test.com
</ns1:NameID>
```
If the email is sent with an hexdigest. How the SP knows who I am? Is there a way to map the user email address with `nameid-format:emailAddress`?

Apologise to keep asking but, does not have more sense, if the local identifier does not want to be sent to the other side to use `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`?  In Pysaml2, if `persistent` is used. It will send the user_id in the SamlResponse. But, regarding to Oasis documentation, `persistent` MUST be random values that have no discernible correspondence with the subject's actual identifier. The intent is to create a non-public, pair-wise pseudonym to prevent the discovery of the subject's identity or activity.

**Comment by rohe** [comment]
Hi Jose,

> 11 feb 2016 kl. 13:07 skrev Jose de Soto <notifications@github.com>:
> 
> But what happens if the third party SP requires that the NameID contain the user email address. Technically:
> 
> <ns1:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" NameQualifier="https://test-proxy.test.com/idp.xml" SPNameQualifier="TestSP" >
> user_name@test.com
> </ns1:NameID>

Well this only says that the name ID format is an emailAddress.
It doesn’t say it has to be a real usable email address :-/

> If the email is sent with an hexdigest. How the SP knows who I am? Is there a way to map the user email address with nameid-format:emailAddress?

Ah, no!
But that doesn’t mean it can’t be done.

> Apologise to keep asking but, does not have more sense,

:-)

> if the local identifier does not want to be sent to the other side to use urn:oasis:names:tc:SAML:2.0:nameid-format:persistent?
> In Pysaml2, if persistent is used. It will send the user_id in the SamlResponse.

Hmm, that is not how it should be !

> But, regarding to Oasis documentation, persistent MUST be random values that have no discernible correspondence with the subject's actual identifier. The intent is to create a non-public, pair-wise pseudonym to prevent the discovery of the subject's identity or activity.

Correct! Will change, wonder how many implement will break because of this.
Them expecting a ’real’ userid.

”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss

**Comment by rmharris157** [comment]
I can tell you this implementation does not work with AWS SSO -- SSO expects that the username will match the NameID /exactly/ as an email address. It would be great if there was a switch in place to toggle between the generated ID or the actual email address.

**Comment by peppelinux** [comment]
@c00kiemon5ter I think that @rmharris157 @josedesoto have right, email format whould be email as simple as possibile.

I didn't testd it right because I never used email as subject id BUT this sound to me that something should be moved to make this aspect clear definitely.

**Comment by peppelinux** [comment]
Hi @josedesoto,
I've finally have a test on this and with pysaml2 v6.1.0 I got an email address format correctly.
I think that we can close this thread, thank you

**Comment by rmharris157** [comment]
> Hi @josedesoto,
> I've finally have a test on this and with pysaml2 v6.1.0 I got an email address format correctly.
> I think that we can close this thread, thank you

@peppelinux As of 6.3.1 is the user's actual email address returned or is it still <longobfuscatedhexstring>@domain.tld? I'm still seeing the latter -- is there a configuration change that I need?

**Comment by peppelinux** [comment]
Ok, i tested It in uniAuth idp. Please tell US more about your asset, which kind of implementation do you have as SP or idp and let's try to figure what's hap

**Comment by rmharris157** [comment]
I'm using the pysaml2 example code as a test IdP with AWS SSO as the SP.
To make this work in the past, I've had to change ident.py:174 from:
`_id = "%s@%s" % (_id, self.domain)` to`_id = "%s@%s" % (userid, self.domain)` where in the proceeding call _id is basically just a hash of the userid.

**Comment by peppelinux** [comment]
Ok, that's the problem, the example code.
You can emplement that example to show the value as you prefer, I would suggest you to use uniauth or djangosaml2idp but that's your business.

I'm closing this now, please open a new issue regarding the example code if needed,
thank you
