### ISSUE TITLE
Are zope.interface and repoze.who really dependencies?

### ISSUE THREAD

**Issue by mbertolacci** [IdentityPython/pysaml2#314]
I'm (happily) using this package with Django, and I noticed that repoze.who and zope.interface both get installed when I install pysaml2. Correct me if I'm wrong, but I don't think the core functionality of the library depends on these.

My understanding of the convention with Python packages is that these non-core dependencies usually don't make it into the requires list, but instead are noted in the documentation as necessary depending on where you use the library.

Would it be possible / desirable to remove these from the requires list?

(This came up for us because we run a private PyPI server for production deployments and have to replicate package dependencies there, and we try to keep it minimal.)

**Comment by rohe** [comment]
> 5 feb 2016 kl. 02:22 skrev Michael Bertolacci <notifications@github.com>:
> 
> I’m (happily) using this package with Django, and I noticed that repozewho and zopeinterface both get installed when I install pysaml2 Correct me if I'm wrong, but I don't think the core functionality of the library depends on these

You’re correct the core library doesn’t depend on those packages.

> My understanding of the convention with Python packages is that these non-core dependencies usually don't make it into the requires list, but instead are noted in the documentation as necessary depending on where you use the library
> 
> Would it be possible / desirable to remove these from the requires list?

It’s possible and it’s a problem I wrestle with all the time.


— Roland
”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss

**Comment by peppelinux** [comment]
https://github.com/IdentityPython/pysaml2/blob/1aeae3ae565e02f863a26b2893354d048a7abff8/setup.cfg#L69

@c00kiemon5ter I think that these could be installed only for unit test purpose if you agree. This would be a good enhancement for future releases

**Comment by peppelinux** [comment]
Hi @mbertolacci,
At this moment this issue was fixed in version 6.1.0, I just checked.
