### ISSUE TITLE
handle_logout_request doesn't sign redirect binding responses as requested

### ISSUE THREAD

**Issue by MrkGrgsn** [IdentityPython/pysaml2#334]
When `saml2.client:handle_logout_request()` is called with `sign=True` and the selected binding is HTTP Redirect, the request is not signed.

Where the error lies is not clear. `apply_binding()` accepts a `sign` param but it is not used for redirect bindings. It instead looks for the `sigalg` param in kwargs. `handle_logout_request()` supplies neither the `sign` nor `sigalg` params to `apply_binding()`

**Comment by peppelinux** [comment]
https://github.com/IdentityPython/pysaml2/issues/595

At this time I found In examples/ idp that it doesn't handle signed logout request

**Comment by peppelinux** [comment]
Done a simple SLO implementation here:
https://github.com/peppelinux/djangosaml2idp/tree/SLO

specifically:
https://github.com/peppelinux/djangosaml2idp/blob/SLO/djangosaml2idp/views.py#L324

It works even if SLO request is signed

**Comment by peppelinux** [comment]
Moving all the aspect of signature in HTTP-REDIRECT binding here:
https://github.com/IdentityPython/pysaml2/issues/633
