### ISSUE TITLE
Issue when verifying signature of IdP

### ISSUE THREAD

**Issue by ganiserb** [IdentityPython/pysaml2#344]
@rohe 
I am using djangosaml2 and have a SP configured to work with an IdP that self-signs its certificates (Salesforce.com), and I've noticed that when I want to do IdP initiated login pysaml2 does not actually verify the signature of the certificate included in the metadata. The certificate I have from the IdP is not even necessary because the metadata signature is not being verified.

Specifically, [these are the lines I see that skip the signature verification](https://github.com/rohe/pysaml2/blob/master/src/saml2/mdstore.py#L634-L639) when [loading external metadata](https://github.com/rohe/pysaml2/blob/master/src/saml2/mdstore.py#L754).

Why is `parse_and_check_signature` returning `True` when `self.signed()` is returning `False`? Is it because the cert is self signed and no checks are performed?

If you need more information, please ask. Thank you.

**Comment by ganiserb** [comment]
@rohe bump

**Comment by ganiserb** [comment]
@rohe bump

**Comment by peppelinux** [comment]
All certificate in my/our SAML2 system are self signed.
pysaml2's metadata store verify metadata signature only if it have been configured also a certificate used for that

Thank you for your question and don't mind the times, I'm sorry
