### ISSUE TITLE
metadata maker is generating empty URI in ServiceName element

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/pysaml2#345]
Pysaml2 is generating an <--ns0:ServiceName xml:lang="en"/> element for the AttributeConsumingService, which is XML schema valid, but not allowed according to SAML core:

1.3.2 URI Values
.. 
Unless otherwise indicated in this specification, all URI reference values used within SAML-defined elements or attributes MUST consist of at least one non-whitespace character ..

**Comment by rhoerbe** [comment]
Ah, my bad, this is not an localizedURIType, it is a localizedNameType. I got confused by the OpenSAML error message

**Comment by rhoerbe** [comment]
jut learned that strings cannot be blank, like URIs:
SAML core 1.3.1 String Values:
... Unless otherwise noted in this specification or particular profiles, all strings in SAML messages MUST consist of at least one non-whitespace character

**Comment by peppelinux** [comment]
Hi @rhoerbe, I can't reproduce this in my asset, I have a SP with a correct valued ACS.
Can give more information about how to reproduce this?

**Comment by rhoerbe** [comment]
I passed on my SATOSA-related projects, so I have no dev env available in the time since. But if pysaml now is creating a proper string value, or no ServiceName at all, then the problem should be fixed.

**Comment by peppelinux** [comment]
Thank you for ack. I close this for now because It looks good to me, if someone Will update this thread I'll open It again

👍

**Comment by melanger** [comment]
@peppelinux This was probably caused by a missing `name` under the `sp` key in config, such as in the example SATOSA SAML2 backend config. I created https://github.com/IdentityPython/SATOSA/pull/393 to address that.
