### ISSUE TITLE
Encrypted assertions

### ISSUE THREAD

**Issue by alex-fr** [IdentityPython/pysaml2#346]
Hi, I have a question, I'm using sp-wsgi example and my SP get assertion from IdP like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://example.com" ID="_0a587520f2bd869df22b20b123" InResponseTo="id-jPHGidHyF785XDpNA" IssueInstant="2016-06-27T09:38:29.394Z" Version="2.0">
   <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">example.com</saml2:Issuer>
   <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
         <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
         <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
         <ds:Reference URI="#_0a587520f2bd869df22b20b8123">
            <ds:Transforms>
               <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
               <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
            <ds:DigestValue>iXWpSW2SXiB09vTYG9XRhn81i6w=</ds:DigestValue>
         </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue> truncated </ds:SignatureValue>
      <ds:KeyInfo>
         <ds:X509Data>
            <ds:X509Certificate> truncated </ds:X509Certificate>
         </ds:X509Data>
      </ds:KeyInfo>
   </ds:Signature>
   <saml2p:Status>
      <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
   </saml2p:Status>
   <saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
      <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_d3167d4187ac2dc27788afae0ae6f6b9" Type="http://www.w3.org/2001/04/xmlenc#Element">
         <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc" />
         <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:RetrievalMethod Type="http://www.w3.org/2001/04/xmlenc#EncryptedKey" URI="#_ff81c81b7e0a314436a31e3b574a83a7" />
         </ds:KeyInfo>
         <xenc:CipherData>
            <xenc:CipherValue>gUfe2uvEuE truncated oh4QWnBC/om4Q==</xenc:CipherValue>
         </xenc:CipherData>
      </xenc:EncryptedData>
      <xenc:EncryptedKey xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_ff81c81b7e0a314436a31e3b574a83a7">
         <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-1_5" />
         <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:X509Data>
               <ds:X509Certificate> truncated </ds:X509Certificate>
            </ds:X509Data>
         </ds:KeyInfo>
         <xenc:CipherData>
            <xenc:CipherValue>ZxwEbo9 truncated laaZVvZ3Sy43j1+rsUSLXFWw==</xenc:CipherValue>
         </xenc:CipherData>
         <xenc:ReferenceList>
            <xenc:DataReference URI="#_d3167d4187ac2dc27788afae0ae6f6b9" />
         </xenc:ReferenceList>
      </xenc:EncryptedKey>
   </saml2:EncryptedAssertion>
</saml2p:Response>
```

How can I get decrypted data from this EncryptedAssertion with pysaml2 and xmlsec1? I have key and I managed to get data with online decrypt service https://www.samltool.com/decrypt.php

**Comment by bazzisoft** [comment]
@alex-fr Did you ever manage to solve this? I'm running into the same problem today & would love an idea to help me solve it!

**Comment by ravindrabhavanam** [comment]
@alex-fr @bazzisoft I am facing the exact problem. Did you manage to solve this?

**Comment by bazzisoft** [comment]
@ravindrabhavanam I believe i did solve it, by adding the encryption keypairs to the config. Try this out on your end and let me know if it works:

    SAML_SP_KEY = os.path.join(SAML_KEYS_PATH, 'key.pem')
    SAML_SP_CERT = os.path.join(SAML_KEYS_PATH, 'cert.pem')

    conf.update({
        'key_file' : SAML_SP_KEY,
        'cert_file' : SAML_SP_CERT,
        'encryption_keypairs': [{
            'key_file' : SAML_SP_KEY,
            'cert_file' : SAML_SP_CERT,
        }]
    })

**Comment by ravindrabhavanam** [comment]
@bazzisoft Thanks for your response. But, I am already having this configuration. I could decrypt the response using the private key when i tried with few online tools but, "parse_authn_request_response" function isn't able to get the subject (because it is unable to get the decrypted content). I was suspecting it to be some issue with the way response xml elements are structured. Below is the response from the IDP. Do you see anything off? It looks exactly similar to @alex-fr 's output. 


<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://example.com" ID="id197863638384131041467048207" InResponseTo="id-n5BTacOkXVBdo0h4s" IssueInstant="2017-04-02T20:09:45.100Z" Version="2.0">
    <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://www.someidp.com/somevalue</saml2:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference URI="#id197863638384131041467048207">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue> truncated </ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
    <ds:SignatureValue> truncated </ds:SignatureValue>
    <ds:KeyInfo>
        <ds:X509Data>
            <ds:X509Certificate> truncated </ds:X509Certificate>
        </ds:X509Data
    </ds:KeyInfo>
    </ds:Signature>
    <saml2p:Status xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"><saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></saml2p:Status>
    <saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
        <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_f8e380f3e6ebc83a688a9f109ff22c37" Type="http://www.w3.org/2001/04/xmlenc#Element">
            <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"/>
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:RetrievalMethod Type="http://www.w3.org/2001/04/xmlenc#EncryptedKey" URI="#_ee366591b735703178fff9bc1481f51b"/>
            </ds:KeyInfo>
            <xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
                <xenc:CipherValue> truncated </xenc:CipherValue>
            </xenc:CipherData>
        </xenc:EncryptedData>
        <xenc:EncryptedKey xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_ee366591b735703178fff9bc1481f51b">
            <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
                <ds:DigestMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            </xenc:EncryptionMethod>
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate> truncated </ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
            <xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
                <xenc:CipherValue> truncated </xenc:CipherValue>
            </xenc:CipherData>
            <xenc:ReferenceList>
                <xenc:DataReference URI="#_f8e380f3e6ebc83a688a9f109ff22c37"/>        
            </xenc:ReferenceList>
        </xenc:EncryptedKey>
    </saml2:EncryptedAssertion>
</saml2p:Response>

**Comment by bazzisoft** [comment]
@ravindrabhavanam I don't see anything wrong with that response, but I'm far from a SAML expert. The way I solved it in the end was debugging & stepping through the PySAML code until I found the point it was failing. It was too hard to figure out from the error messages. Eventually you will be able to see whether the SAML response is passed to the xmlsec binary for decryption and if so, what the output/error is. There's quite a bit of code to walk through but I don't have any better ideas unfortunately.

**Comment by jkakavas** [comment]
`parse_assertion` needs to be passed the encryption keys in order for it to try and decrypt it
https://github.com/rohe/pysaml2/blob/master/src/saml2/response.py#L900

I'm closing this as I don't see how this is a generic error in pysaml2, @ravindrabhavanam feel free to come back with more feedback if you still face the same issue

**Comment by bazzisoft** [comment]
@jkakavas I wonder if it's worth adding the "encryption" config option to the documentation? Seems a few people have run into this issue because there is no indication of how to get it configured for encryption/decryption. Maybe on this page: https://pysaml2.readthedocs.io/en/latest/howto/config.html#complete-example

**Comment by jkakavas** [comment]
@bazzisoft Can you clarify which part would make sense adding to the documentation ? 

There would be nothing more required than what is already there 
```
"key_file" : "./mykey.pem",
"cert_file" : "./mycert.pem",
```
for the SP to be able to handle encrypted assertions

**Comment by bazzisoft** [comment]
@jkakavas This didn't work for me, i needed some additional configuration which I determined from looking into the code:

    {
        'key_file' : './mykey.pem',
        'cert_file' : './mycert.pem',
        'encryption_keypairs': [{
            'key_file' :  './mykey.pem',
            'cert_file' : './mycert.pem',
        }]
    }

**Comment by jkakavas** [comment]
Interesting.. Would you be able to provide a test case or scenario where this doesn't work for you without the extra parameters?  I am currently using it in production with no issues whatsoever in handling encrypted assertions

**Comment by bazzisoft** [comment]
Sure, i was using it with http://www.testshib.org/ when it was failing and the above config fixed it.

Using PySAML version: `pysaml2>=4.4,<4.5`

**Comment by ravindrabhavanam** [comment]
Same with me. I also had to use 'encryption_keypairs' to get the decryption of SAML Response work.
Also, I ran into some other issue #412 because of ID_ATTR mismatch (Id vs. ID).

**Comment by jkakavas** [comment]
You are right, I just verified this. I would say that this is a problem with the example sp (sp-wsgi) rather than with pysaml2 as a library* but I will reopen this so that we can look into it in more detail


* satosa SP part handles this like [this](https://github.com/SUNET/SATOSA/blob/master/src/satosa/backends/saml2.py#L66)

**Comment by bazzisoft** [comment]
Yeah I don't think this is a bug rather just an undocumented feature that could be made easier to find. It would be super nice if the library would default the encryption keypairs to the regular signing keypair if they're not explicitly provided, as that seems to be a sensible default, demonstrated in your example above. But I'm not sure if that is possible with respect to backwards compatibility.

**Comment by peppelinux** [comment]
Probably this have been fixed here:
https://github.com/IdentityPython/pysaml2/commit/ccdfd634e71f32016bf10291209b063b509e4f36

correct me if I'm wrong, if it is true this issue will be closed in weeks
