### ISSUE TITLE
Disable Debug Logging

### ISSUE THREAD

**Issue by chukkwagon** [IdentityPython/pysaml2#350]
I'm hoping to use this package in a production environment, but first i need a way to disable/override the default logging settings. Right now, there is a lot of logging 'noise' generated whenever the package runs during an sso protocol. I can't find anywhere in the documentation that describes how to disable logging for the platform or limit logging to only errors. Is there something I'm missing in the documentation? thanks

**Comment by jkakavas** [comment]
How are you using pysaml2 ? Are you using an example sp/idp from the example directory ? Are you building your own?

**Comment by chukkwagon** [comment]
I ended up using another package, don't remember off the top of my head how i had configured it to run, but i do know i followed the documentation for a SP setup.
