### ISSUE TITLE
Minimal example?

### ISSUE THREAD

**Issue by copumpkin** [IdentityPython/pysaml2#362]
I'm feeling a bit overwhelmed trying to follow the documentation and examples, and was wondering if anyone had considered a very simple "full chain" fully autonomous example without too much other stuff going on. Something like:
1. Provide a key/cert to example program
2. Example makes a simple IdP with minimal config that makes sense
3. Example makes a simple signed assertion
4. Example (possibly in separate function to demonstrate different parties) checks validity of assertion produced in step 3

And that's it. It seems like it could demonstrate the most basic SAML building blocks along with the associated pysaml2 classes that are needed. Having such a thing would certainly help me, since the 1000+ lines of the existing examples, interleaved with web frontends, configurations, and various other non-essential concerns make it quite hard for me to follow.

**Comment by sbuzonas** [comment]
I'm just starting to look at the examples and feeling the same way about it.  I haven't been able to get the example running yet.  Once I figure that out, I'm going to rewrite each piece minimally and I'll get back to you if I get anywhere.

**Comment by skapin** [comment]
@sbuzonas any news ?

**Comment by kurtbrose** [comment]
lol I'm having the same experience, I guess since it has been 4 years this is kind of dead

**Comment by peppelinux** [comment]
Here's mine

Saml2 IdP
https://uniauth.readthedocs.io/en/latest/

Saml2 SP: see djangosaml2

**Comment by peppelinux** [comment]
Hope that the last updates on pysaml2 documentation helps, and also that examples coming from djangosaml2 and other pysaml2 wrappers as well.

**Comment by bjm88** [comment]
> Here's mine
> 
> Saml2 IdP https://uniauth.readthedocs.io/en/latest/
> 
> Saml2 SP: see djangosaml2

Hi @peppelinux your link doesn't work above anymore..
Also looking for simple IDP setup, mainly flask based IDP initiated SSO (unsolicited), thanks!

**Comment by peppelinux** [comment]
Here

https://uniauth.readthedocs.io/
