### ISSUE TITLE
create AuthnRequest without passing assertion_consumer_service_url in kwargs

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/pysaml2#380]
Base.create_authn_request() requires an assertion_consumer_service_url kwarg. If missing it fails with an NoneType exception.

1. The ACS should not be mandatory, in fact, as pysaml requires metadata configuration of entities, the ACS can be taken from metadata in the regular case. Action: support AuthnRequests without ACS.
2. API signatures should be explicit an not rely on **kwargs. Also, there is a binding parameter that seems to have the same purpose as the acs kwarg. However, it is not take although specified. Action: -> deprecate the acs kwarg, make the binding param working.

**Comment by rohe** [comment]
It doesn't fail on no assertion_consumer_service_url in kwargs.
If there is no assertion_consumer_service_url in kwargs it will fall back on using the default binding.
That is, on v4.4.0 that's how it is.

**Comment by rhoerbe** [comment]
I was not clear: It fails when passing no ACS and setting binding=None.

I will send you a PR when you have accepted the one for issue#345

**Comment by rhoerbe** [comment]
Or see https://github.com/rhoerbe/pysaml2/blob/dev_r2h2/src/saml2/client_base.py#L238

**Comment by rhoerbe** [comment]
May I nudge you to answer this?

**Comment by peppelinux** [comment]
@rhoerbe don't know if it still is this way, please give me a feedback to keep this alive.
I faced this kind of problems and found my way to go ahead, I simply use pysaml2 internal to build my objects. See here, I built an AuthnRequest simply from scratch, deciding each attribute in detail:
https://github.com/peppelinux/Django-Identity/blob/36cf34a3d7f1e10edf7414c350f5025a599e5b8f/djangosaml2_sp/djangosaml2_sp/djangosaml2_spid/views.py#L142

Hope that this would help to close with thread but fill free to ask to reopen this if needed, thanx

**Comment by rhoerbe** [comment]
let us keep it closed
