### ISSUE TITLE
Pyinstaller not supported

### ISSUE THREAD

**Issue by arvindsree** [IdentityPython/pysaml2#381]
Hi there,

Looks like pyinstaller support is not present. Probably the issue is with pyinstaller. Anyway I have posted the bug in the pyinstaller issues section as well. 

Maybe there could be some sort of quick fix to enable pyinstaller or other distutil support?

Traceback .

```
Traceback (most recent call last):
File "saml.py", line 67, in <module>
File "saml.py", line 62, in main
File "saml2/config.py", line 341, in load
File "saml2/config.py", line 251, in load_special
File "saml2/config.py", line 271, in load_complex
File "saml2/attribute_converter.py", line 80, in ac_factory
File "importlib/init.py", line 37, in import_module
ImportError: No module named adfs_v1x
```

Code .

```

from saml2 import (
    BINDING_HTTP_POST,
    BINDING_HTTP_REDIRECT,
    BINDING_HTTP_ARTIFACT
)

from saml2.client import Saml2Client
from saml2.config import Config as Saml2Config
import requests


def main():
    acs_url = "http://ip:5000/acs"
    https_acs_url = acs_url
    rv = requests.get("https://dev-978392.oktapreview.com/app/exk87z3e9swnuRfct0h7/sso/saml/metadata")
    settings = {
        'metadata': {
            'inline': [rv.text],
            },
        'service': {
            'sp': {
                'endpoints': {
                    'assertion_consumer_service': [
                        (acs_url, BINDING_HTTP_REDIRECT),
                        (acs_url, BINDING_HTTP_POST),
                        (https_acs_url, BINDING_HTTP_REDIRECT),
                        (https_acs_url, BINDING_HTTP_POST)
                    ],
                },
                'allow_unsolicited': True,
                'authn_requests_signed': False,
                'logout_requests_signed': True,
                'want_assertions_signed': True,
                'want_response_signed': False,
            },
        'entityid': 'http://ip:5000/' #should be set to actual IP but its unused

        },
    }
    spConfig = Saml2Config()
    spConfig.load(settings)
    spConfig.allow_unknown_attributes = True
    saml_client = Saml2Client(config=spConfig)
    print dir(saml_client)

main()
```

I tried --onefile --onedir options and hidden import of saml2
Ubuntu 14.04, python 2.7.12, pyinstaller 3.3.dev0-b78bfe5, pysaml2 4.3.0

**Comment by rohe** [comment]
Hi yourself,

> On 01 Nov 2016, at 12:24, Arvind <notifications@github.com> wrote:
> Looks like pyinstaller support is not present. Probably the issue is with pyinstaller. Anyway I have posted the bug in the pyinstaller issues section as well.
> 
> Maybe there could be some sort of quick fix to enable pyinstaller or other distutil support?
> 
> Traceback .
> 
> Traceback (most recent call last):
> File "saml.py", line 67, in <module>
> File "saml.py", line 62, in main
> File "saml2/config.py", line 341, in load
> File "saml2/config.py", line 251, in load_special
> File "saml2/config.py", line 271, in load_complex
> File "saml2/attribute_converter.py", line 80, in ac_factory
> File "importlib/init.py", line 37, in import_module
> ImportError: No module named adfs_v1x
> 
> Ubuntu 14.04, python 2.7.12, pyinstaller 3.3.dev0-b78bfe5, pysaml2 4.3.0
> 
> 

So, it can’t find adfs_v1x which is weird since your running 4.3.0 of pysaml2.
Just to check, can you verify that you have:

saml2/attributemaps/adfs_v1x.py

$ python3
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from saml2.attributemaps import adfs_v1x
>>>

— Roland

**Comment by arvindsree** [comment]
Hello Roland,

Thank you for the reply.  The file is present at

/usr/local/lib/python2.7/dist-packages/saml2/attributemaps/adfs_v1x.py

Does it mean that pyinstaller will not search those directories for the specific file import?
Also, are you able to recreate the issue?

Thanks,
Arvind

**Comment by lukedd** [comment]
The problem here is the use of `importlib.import_module` in pysaml2, which prevents pyinstaller from discovering which modules it needs to include in the frozen package.

See the pyinstaller documentation about "hidden imports":
https://pythonhosted.org/PyInstaller/when-things-go-wrong.html#listing-hidden-imports

**Comment by peppelinux** [comment]
Thank you @lukedd for clarifing this

**Comment by arvindsree** [comment]
Hidden import of saml2 did not help as per the original comment. I finally got it working. This is the configuration that I used. Hoping that it is useful to someone.

```
      hiddenimports=["pkg_resources.py2_warn", "pkg_resources.markers", "saml2", "saml2.attributemaps.adfs_v1x",
                 "saml2.attributemaps.adfs_v20", "saml2.attributemaps.basic", "saml2.attributemaps.saml_uri",
                 "saml2.attributemaps.shibboleth_uri"]
```

You would also need a hook 
```
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('pysaml2')
```
