### ISSUE TITLE
algsupport extension

### ISSUE THREAD

**Issue by lambdafu** [IdentityPython/pysaml2#382]
Hi,

is there a way to supply multiple DigestMethod and SigningMethod elements in the config?  It seems to me there can only be one such key in the config, I tried giving lists at several levels, none of them worked.

Also, shouldn't there be a way to query the supported methods from the library?

Thanks!

**Comment by peppelinux** [comment]
Yes if these PR will be continue to be followed, developed (and desired!)

https://github.com/IdentityPython/pysaml2/pull/645
https://github.com/IdentityPython/pysaml2/pull/628
https://github.com/IdentityPython/pysaml2/pull/597

**Comment by peppelinux** [comment]
Moving this thread here, thank you
https://github.com/IdentityPython/pysaml2/issues/421
