### ISSUE TITLE
Exclude tests/ directory from dist

### ISSUE THREAD

**Issue by orf** [IdentityPython/pysaml2#383]
I think it's a mistake to bundle the entire `tests/` directory with the package. The directory is currently 26 megabytes!

This can be excluded in the setup.py, would it be an issue to do this?

**Comment by jkakavas** [comment]
Looking at https://github.com/rohe/pysaml2/blob/9cbbd9bd9f6bfa5e9ceace064dd1af4e2ff2f68c/setup.py#L45, I believe this is already solved
