### ISSUE TITLE
ImportError: No module named Cryptodome

### ISSUE THREAD

**Issue by schettino72** [IdentityPython/pysaml2#389]
```
  File "./idp.py", line 25, in <module>
    from saml2.authn import is_equal
  File "/mnt/work/_third/pysaml2/src/saml2/authn.py", line 5, in <module>
    from saml2.aes import AESCipher
  File "/mnt/work/_third/pysaml2/src/saml2/aes.py", line 6, in <module>
    from Cryptodome import Random
ImportError: No module named Cryptodome
```

"Swap pycrypto* for pyca/cryptography" was incomplete: https://github.com/rohe/pysaml2/commit/afdf5b4a8cca33dbe746095d9442b958c5fa9a24

**Comment by sigmavirus24** [comment]
@schettino72 there appear to be no tests for the `aes` module. Please contribute some tests (so we can verify backwards compatibility) and we'll update that module to use `cryptography` as well. Until then, there's too much risk for a regression or bug in swapping it.

**Comment by schettino72** [comment]
I understand you dont want to touch the code without tests but making it completely broken doesnt help much.

I guess the incomplete patch needs to be reverted or at least re-add cryptodome as a dependency. 
Sorry but I dont have time to add tests myself.

**Comment by sigmavirus24** [comment]
Reverting to a hostile fork of an insecure library seems irresponsible at best.

You can also simply install PyCryptodome yourself to unbreak this.

**Comment by MiklinMA** [comment]
edit saml2/aes.py

```
6,7c6,7
< from Cryptodome import Random
< from Cryptodome.Cipher import AES
---
> from Crypto import Random
> from Crypto.Cipher import AES
```

**Comment by c00kiemon5ter** [comment]
I think one only needs to install [`pycryptodomex`][cr].

  [cr]: https://pypi.org/project/pycryptodomex/

**Comment by c00kiemon5ter** [comment]
Pull Request #515 removes the need for `pycryptodomex` or `pycryptodome`.

**Comment by sudo-WearTherinG** [comment]
i was missing module cryptodomex.hash
i fixed the missing module using this command
**pip install "pycryptodomex==3.9.7"**

**Comment by anreciomartin** [comment]
> i was missing module cryptodomex.hash
> i fixed the missing module using this command
> **pip install "pycryptodomex==3.9.7"**

Great !!,   runs fine  your  solution.   Thanks!!
