### ISSUE TITLE
create_discovery_service_request does not check for querypart in url

### ISSUE THREAD

**Issue by mrvanes** [IdentityPython/pysaml2#402]
If url contains a querypart (?...) client_base.create_discovery_service_request creates an invalid return value containing multiple queryparts (?...?...). I fixed it by modifying client_base.py@819

```        params = urlencode(args)
        part = urlparse(url)
        if part.query:
            return_url = "%s&%s" % (url, params)
        else:
            return_url = "%s?%s" % (url, params)

        return return_url
```
(I copied the code from discovery.py)

Do you want a pull request instead?

**Comment by peppelinux** [comment]
Hi @mrvanes have you any updates for this?
we should decide whether to seriously discuss your possible PR, isn't tru @c00kiemon5ter ?

**Comment by mrvanes** [comment]
I see it has been fixed, so this issue can be closed.
https://github.com/IdentityPython/pysaml2/blob/1aeae3ae565e02f863a26b2893354d048a7abff8/src/saml2/client_base.py#L926
