### ISSUE TITLE
Please refrain from running ac_factory if not explicitly asked for

### ISSUE THREAD

**Issue by mrvanes** [IdentityPython/pysaml2#403]
I've been struggling with satosa failing internal atrribute mapping because pysaml2 had converted my incoming long SAML urn based attributes to shortnames before any custom attribute mapping was applied. This caused unexpected behaviour because I expected the internal mapping to be able to operate on original received long urn format attributes but was forced to map shortnames to internal representation instead.
This is unexpected, non standard behaviour and should preferably be disabled unless explicitly requested by config parameter like e.g. use_ac_factory_map.

I fixed the problem by inserting a ```   acs = [] ``` just before ```   _acs = self.getattr("attribute_converters", typ)``` in config.py@277 to simply circumvent the "No attribute converters" exception above.

**Comment by jkakavas** [comment]
I disagree that this is "unexpected" or "non standard" (according to which spec? I mean satosa is a XtoY proxy and needs an internal representation that is consistent between all Xs and Ys .
Not sure if we should handle this in pysaml2 or satosa

**Comment by mrvanes** [comment]
Ok, I was a bit frustrated at the time I wrote that, so "non standard" might have been a bit harsh. But my message is still the same: What's wrong with representing "urn:foobar" internally as "urn:foobar" if I asked the IdP's to send me "urn:foobar" so I can write my config/code to handle "urn:foobar"? If I wanted to handle "foobar", I'd ask the IdP's to send me "foobar" instead, wouldn't I?

I understand that not all IdP's are able/knowledgable about what their IdP software does or how it works (ADFS comes to mind) and I also understand that there are some specs that say that some attributes mean te same but that's an agreement I should consciously choose to rely on, not be forced upon me preferably?

**Comment by jkakavas** [comment]
I see your point. For the time being, you can set the configuration option `attribute_map_dir` to an empty directory in order to produce an empty acs ( instead of overriding the code in config.py ). 

The use of internal representations have been a conscious decision from @rohe AFAIK, but I would think that nothing breaks when no attribute maps are provided. ( Assuming the deployer knows that and i.e. filters on urn:oid values and/or uses these values in other software such as satosa ) . That would surely break some of our tests but we need to look into it. 

I would suggest that we add a configuration parameter that allows for no attribute mapping instead of the "ugly hack" of providing an empty directory, PR's are welcome.

**Comment by mrvanes** [comment]
That doesn't work:
```
Sep 25 10:30:42 proxy1 gunicorn[23558]: [2017-09-25 10:30:42] [ERROR]: Failed to create WSGI app.
Sep 25 10:30:42 proxy1 gunicorn[23558]: Traceback (most recent call last):
Sep 25 10:30:42 proxy1 gunicorn[23558]: File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/proxy_server.py", line 141, in make_app
Sep 25 10:30:42 proxy1 gunicorn[23558]: return ToBytesMiddleware(WsgiApplication(satosa_config))
Sep 25 10:30:42 proxy1 gunicorn[23558]: File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/proxy_server.py", line 89, in __init__
Sep 25 10:30:42 proxy1 gunicorn[23558]: super().__init__(config)
Sep 25 10:30:42 proxy1 gunicorn[23558]: File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/base.py", line 43, in __init__
Sep 25 10:30:42 proxy1 gunicorn[23558]: self.config["INTERNAL_ATTRIBUTES"])
Sep 25 10:30:42 proxy1 gunicorn[23558]: File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/plugin_loader.py", line 45, in load_backends
Sep 25 10:30:42 proxy1 gunicorn[23558]: config["BASE"], internal_attributes, callback)
Sep 25 10:30:42 proxy1 gunicorn[23558]: File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/plugin_loader.py", line 179, in _load_plugins
Sep 25 10:30:42 proxy1 gunicorn[23558]: plugin_config["name"])
Sep 25 10:30:42 proxy1 gunicorn[23558]: File "/opt/satosa/satosa-env/lib/python3.5/site-packages/satosa/backends/saml2.py", line 61, in __init__
Sep 25 10:30:42 proxy1 gunicorn[23558]: sp_config = SPConfig().load(copy.deepcopy(config[self.KEY_SP_CONFIG]), False)
Sep 25 10:30:42 proxy1 gunicorn[23558]: File "/opt/satosa/satosa-env/lib/python3.5/site-packages/saml2/config.py", line 350, in load
Sep 25 10:30:42 proxy1 gunicorn[23558]: self.load_complex(cnf, metadata_construction=metadata_construction)
Sep 25 10:30:42 proxy1 gunicorn[23558]: File "/opt/satosa/satosa-env/lib/python3.5/site-packages/saml2/config.py", line 276, in load_complex
Sep 25 10:30:42 proxy1 gunicorn[23558]: "No attribute converters, something is wrong!!")
Sep 25 10:30:42 proxy1 gunicorn[23558]: saml2.config.ConfigurationError: No attribute converters, something is wrong!!
Sep 25 10:30:42 proxy1 gunicorn[23558]: [2017-09-25 10:30:42 +0000] [23558] [INFO] Shutting down: Master
Sep 25 10:30:42 proxy1 gunicorn[23558]: [2017-09-25 10:30:42 +0000] [23558] [INFO] Reason: Worker failed to boot.
Sep 25 10:30:42 proxy1 systemd[1]: satosa.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Sep 25 10:30:42 proxy1 systemd[1]: satosa.service: Unit entered failed state.
Sep 25 10:30:42 proxy1 systemd[1]: satosa.service: Failed with result 'exit-code'.
```

**Comment by mrvanes** [comment]
I managed to create an empty MAP, but now the frontend doesn't hand-out any attributes anymore. It's a bit trickier than that I'm affraid.

**Comment by c00kiemon5ter** [comment]
I am closing this, as it is tracked by #549
