### ISSUE TITLE
Please document MDQ usage

### ISSUE THREAD

**Issue by bajnokk** [IdentityPython/pysaml2#410]
Hi all,

apparently PySAML supports MDQ, but it is not mentioned in the documentation. I was able to get it working by the following config snippet:

```
  metadata:
      mdq:
          https://mdx.domain.com: null
```

I'm not sure if it's the correct one and I couldn't find a way to instruct PySAML to verify the signature of MDX server responses. Please extend the documentation to cover this.

Thank you!

**Comment by jkakavas** [comment]
I touched upon this on #448 a little bit, and the metadata consumption documentation does need some more enhancements. You can try to use the cert parameter as you would do when dealing with remote metadata

**Comment by peppelinux** [comment]
I found this usage reference here
https://github.com/IdentityPython/pysaml2/blob/master/docs/howto/config.rst#metadata
