### ISSUE TITLE
identify() fails with UnicodeEncodeError on non-SAML related POSTs

### ISSUE THREAD

**Issue by MrkGrgsn** [IdentityPython/pysaml2#411]
The `SAML2Plugin.identify()` function is generating a UnicodeEncodeError exception when POSTs with a binary file upload (e.g., PDF or PNG) or form fields have values containing unicode chars. These POSTs are part of the application and are not SAML2 messages. The endpoints for this SP are configured like this:
```
            'endpoints': {
                'assertion_consumer_service': ['https://domain.com/data/saml2/sso'],
                'single_logout_service' : [('https://domain.com/data/saml2/slo',
                    BINDING_HTTP_REDIRECT)],
             },
```
The requests that generate the exceptions are like `/data/dataset/new_resource/dataset-xyz` and `/data/dataset/edit/dataset-xyz`.

I expect that `identify()` should `return None` as soon as possible if the requested URL doesn't match any of the configured assertion consumer, artifact resolution (?), or single logout service endpoints, and in such cases doesn't attempt to parse the post data or querystring.

**Comment by smotornyuk** [comment]
@rohe here's quick solution for this problem, but it assumes that there are no any additional endpoints mentioned by @MrkGrgsn , only  assertion consumer and logout service . 
```diff
diff --git a/src/saml2/s2repoze/plugins/sp.py b/src/saml2/s2repoze/plugins/sp.py
index 1a873551..71687077 100644
--- a/src/saml2/s2repoze/plugins/sp.py
+++ b/src/saml2/s2repoze/plugins/sp.py
@@ -459,9 +459,18 @@ def identify(self, environ):
 
         uri = environ.get('REQUEST_URI', construct_url(environ))
 
-        logger.debug('[sp.identify] uri: %s', uri)
+        handled_urls = (
+            self.conf.endpoint('assertion_consumer_service') +
+            self.conf.endpoint('single_logout_service')
+        )
+        for item in handled_urls:
+            if ~item.find(uri):
+                break
+        else:
+            logger.debug('[sp.identify] uri passed: %s', uri)
+            return
 
-        query = parse_dict_querystring(environ)
+        logger.debug('[sp.identify] uri: %s', uri)
         logger.debug('[sp.identify] query: %s', query)
 
         if "SAMLResponse" in query or "SAMLRequest" in query:
```

**Comment by peppelinux** [comment]
Too much time on a pending question, probably it's time to close this issue.
Ask to reopen this if some indication about how to reproduce this exception would come in advance.
Thank you, whatever my hands are doing ...
