### ISSUE TITLE
Passing attributes isn't obvious, default idp_conf.py is very limiting

### ISSUE THREAD

**Issue by catmeme** [IdentityPython/pysaml2#414]
This might not be obvious to everyone that the default [idp_conf.py](https://github.com/rohe/pysaml2/blob/master/example/idp2/idp_conf.py.example#L105) will filter all your attributes except `eduPersonTargetedID`.

We were able to crack the case with the following notes in this test: https://github.com/rohe/pysaml2/blob/master/tests/test_20_assertion.py#L840-L858

By removing the items in the `entity_categories`, all attributes will pass through:

```
            "policy": {
                "default": {
                    "lifetime": {"minutes": 15},
                    "attribute_restrictions": None, # means all I have
                    "name_form": NAME_FORMAT_URI,
                    "entity_categories": []
                },
            },
```

**Comment by peppelinux** [comment]
If EC is in policy YES, they acts like a filter.
if EC are placed here instead:
https://github.com/UniversitaDellaCalabria/uniAuth/blob/b93734eba00290a7efcf9a5e95a917cbe58bfd8e/django_idp/idp_pysaml2.py.example#L49

they works like a like a business card, just to tell from wich category belong to (but without any excluding filter).
Hope that it help
