### ISSUE TITLE
How to run slo in example?

### ISSUE THREAD

**Issue by victorfence** [IdentityPython/pysaml2#427]
Hi, I want to learn single logout by debugging the example, but what I found, is just login on idp and redirect to sp(a white page), How can I issue a post to idp for single logout? thanks!!

**Comment by peppelinux** [comment]
I'm implementing SLO and I found probably a bug in https://github.com/IdentityPython/pysaml2/issues/595

Bytheway you should view a Page with content and not a blank One

**Comment by peppelinux** [comment]
See https://github.com/IdentityPython/pysaml2/issues/334#issuecomment-474407731

**Comment by peppelinux** [comment]
I'm closing this with the goal to follow these topics in a single thread. Thank you
