### ISSUE TITLE
Handling for urn:oasis:names:tc:SAML:2.0:status:Requester

### ISSUE THREAD

**Issue by goetzk** [IdentityPython/pysaml2#443]
Hi,

I've just spent some time trying to figure out the error at the bottom of the post and after searching through SAML dumps I discovered 
```
<samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester" /><samlp:StatusMessage>SAML_SIGNATURE_INVALID</samlp:StatusMessage></samlp:Status>
```
and similar messages; the key similarity being the status blaming requester.

Would it be possible to catch these errors before they fall through and cause counter intuitive messages like the one below?
https://github.com/rohe/pysaml2/blob/master/src/saml2/saml.py#L1638

If its impractical I'll put this down to experience and move on but i hope you will consider a change to the error handling should this be a code issue rather than completely user error.

```
Request Method: | POST
-- | --
https://example.com/VIP/acs/
1.8.18
MustValueError
If no statement MUST contain a subject element
/usr/local/lib/python2.7/dist-packages/saml2/saml.py in verify, line 1643
/usr/bin/python
2.7.13
['/srv/symantectest/symantectest/attribute-maps',  '/srv/symantectest',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Thu, 17 Aug 2017 00:25:05 +0000
```

**Comment by peppelinux** [comment]
IT should be investigated again
@goetzk have you any updates regarding the latter pysaml2 release, we could start again this thread that I found very interesting

**Comment by goetzk** [comment]
Hi,
I have not worked on saml projects for some time so don't have anything further to add, sorry.

Karl
