### ISSUE TITLE
nameid-format:unspecified

### ISSUE THREAD

**Issue by ekreiser** [IdentityPython/pysaml2#455]
why did you defined it as a 2.0 format?

         urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified

when the standard only defines a 1.1 version of the unspecified nameid

          urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified

this is causing compatability issues working with certain IDP's

**Comment by c00kiemon5ter** [comment]
Fixed by 018a414f4b22f2dad7b2bcf8cf82f40efd1dcc91
