### ISSUE TITLE
Support generic incoming response validation 

### ISSUE THREAD

**Issue by jkakavas** [IdentityPython/pysaml2#465]
We now support explicit setting of `want_assertions_signed` and `want_response_signed` that will, as the name suggests, validate that the SAML Assertion(s) of an incoming SAML response, or the SAML Response itself are signed correctly and fail otherwise. 

I believe we need to allow for an `either or` configuration of the two above that would allow users to configure a pysaml2 based SP to receive any combination of signed assertions and signed responses ( in a similar way to what Shibboleth SP does for instance )

**Comment by jkakavas** [comment]
Nope,

We need a configuration option that will allow either signed Assertions or
signed responses ( one of the two needs to be signed, otherwise we can't
enforce incoming message integrity)

Some IdPs might sign responses, some other might sign the whole response so
it's convenient to handle both cases of needed, and we can't do that now.

Is this clearer?

**Comment by skoranda** [comment]
In the meantime is there a workaround when you have to federate with multiple IdPs and some sign only the response and others sign only the assertion?

**Comment by c00kiemon5ter** [comment]
#485 addresses this issue.
