### ISSUE TITLE
Large python package on pypi

### ISSUE THREAD

**Issue by ad-m** [IdentityPython/pysaml2#481]
Hello,

On [pypi](https://pypi.python.org/pypi/pysaml2) there is package ``pysaml2-4.5.0.tar.gz`` which size is 19MB. This is relatively much, considering the small amount of actual code. The tests weigh about 95% of the archive. Most library users who install it via pypi do not need any tests at all. 
I suggest:

- install wheel on deployment machine (```pip install wheel```),
-  use ``bdist`` command when prepare a new release,
- read https://docs.python.org/3.6/distutils/builtdist.html .

I recommend using following build & release command:
```
python setup.py dist upload;
python setup.py bdist bdist_wheel upload;
```

**Comment by c00kiemon5ter** [comment]
I removed tests for now. The _next_ release will not bundle them. We will revisit this choice in the future.
