### ISSUE TITLE
If the SAML attributes contain unicode characters and logger is debug enabled, then it throws exceptions

### ISSUE THREAD

**Issue by pjsg** [IdentityPython/pysaml2#482]
There are a number of places in `master` where `logger.debug` is called to dump out assertions and the like. If the assertion contains a unicode character (such as in the user's name) then the logger fails as it tries to format the object into a `str`. This is on python 2.7.

**Comment by peppelinux** [comment]
Hi @pjsg
time passed and I think that this issue have been resolved with the latest code refactor regarding logging features.

If you have any feedback to this please reply, otherwise this thread will be closed in weeks
