### ISSUE TITLE
Bearer verification fails if URL is passed as only IP addresses are expected.

### ISSUE THREAD

**Issue by micael-grilo** [IdentityPython/pysaml2#487]
Hi all, 

I'm getting a "saml2.validate.NotValid : NotValid: address" when i get a SAML Response message.

The issue is that the code is only expecting an IPV4 or IPV6 address, but in my case i get a URL passed as parameter on "[if not valid_address(data.address):](https://github.com/rohe/pysaml2/blob/9e6ddc0030828a17fe44a3ecdc5c95b6b6c8d741/src/saml2/response.py#L677)" my "data.address" is something like "http://domain.com/etc..." that causes validation error.

What's the purpose of this validation? Can we validate url's as well? 
I've coded a local fix to bypass this issue, but it would be great to have it fixed on source, let me know if I can help with this.

Best,

**Comment by peppelinux** [comment]
Hi @micael-grilo, still no reply to this.
Can you give us more information about how to reproduce this strange beahviour?

please give us a reply otherwise this thread will be closed in weeks
thank you

**Comment by micael-grilo** [comment]
@peppelinux we can cloe this. ;) thanks

**Comment by Littlefisher619** [comment]
Why the address can't be strings like "ip:port"?
The verification rule is too strict! The address format like "ip:port" can't be think as malformed.
The idp sent client's address within the SubjectConfirmationData section, but the `address` may not always a ip address only, it may contains port which determine by the implemention of idp. 
I got a `saml2.validate.ShouldValueError: Not an IPv4 or IPv6 address` while setting up my service provider.

![image](https://user-images.githubusercontent.com/8090425/149946768-ee68de38-36d5-4c80-b3bf-b2bd94a26c08.png)

![image](https://user-images.githubusercontent.com/8090425/149947954-35dbf962-2eaa-4a8d-9a66-c9465f79c66e.png)
