### ISSUE TITLE
Question regarding SP metadata and authn_requests_signed attribute

### ISSUE THREAD

**Issue by ksshetty** [IdentityPython/pysaml2#500]
Hi folks,

I have been successfully been able to use the pysaml2 library to write an SP application that integrates with a handful of IdPs. I have two questions:

1. One of the IdPs wants access to the SP metadata and I wasn't sure how to generate/share this info to provide to the IdP. I found some good info on the following URL but I didn't understand how to generate the metadata: [link to documentation](https://github.com/IdentityPython/pysaml2/blob/master/doc/howto/config.rst)

2. I notice the `authn_requests_signed` attribute can be used to sign the requests made from the SP side. In order to do this, the SP needs to sign the request using the private key and share the public key with the IdP. But what was not clear to me is how does the library look for the cert on the SP side? [link to documentation](https://github.com/IdentityPython/pysaml2/blob/master/doc/howto/config.rst#authn-requests-signed)

Any help or pointers will be greatly appreciated. Thanks in advance.

Karthik

**Comment by c00kiemon5ter** [comment]
1. To generate the metadata you need to give your configuration file to the [`make_metadata.py`](https://github.com/IdentityPython/pysaml2/blob/7135d5370425b5a0fb18ddd604779f6195fc3306/tools/make_metadata.py) script. If you have installed pysaml2 you should have that script available as a command.

```
make_metadata.py sp_conf.py > metadata.xml
```

2. You specify the [private key][key] and the [public certificate][cert] on the configuration. 

Check the [example configuration][exconf] and the [example SP docs][exsp]

[cert]: https://github.com/IdentityPython/pysaml2/blob/master/doc/howto/config.rst#cert-file
[key]: https://github.com/IdentityPython/pysaml2/blob/master/doc/howto/config.rst#key-file
[exsp]: https://github.com/IdentityPython/pysaml2/blob/master/doc/examples/sp.rst
[exconf]: https://github.com/IdentityPython/pysaml2/blob/master/example/sp-wsgi/sp_conf.py.example#L40-L41

**Comment by ksshetty** [comment]
Thank you so much @c00kiemon5ter This info was very helpful.
