### ISSUE TITLE
wantAssertionSigned trouble

### ISSUE THREAD

**Issue by skapin** [IdentityPython/pysaml2#512]
Running the idp2 example

## Expected Behavior
Binding with an external SP, and login/logout 

## Current Behavior
When I try to log from the SP (which redirect me to the IDP2 login form), i put the good credential, but on validation, the SP tell me that : 

```
2018-06-27T11:53:19.060Z |    ERROR | requestId=[suzO7ADp4D], url=[/public/sp/SSO], status=[401], cause=[Error validating SAML message; caused by: Metadata includes wantAssertionSigned, but neither Response nor included Assertion is signed], displayableMessage=[null], exceptionClass=[null]
```

## Possible Solution
Looks like SP want signed assertion or response:

```
Identity Provider does not sign SAML assertions.
Verify your IdP configuration.
``` 
find in some saml doc

I can't find how to do that or any information on pysaml2

any help is welcomed

**Comment by skapin** [comment]
More information : After diging in code, i can find that the certificate present in authnrequest is NOT detected by pysaml2idp. So he doesnt put the cert in response, and so, my SP is not happy about it.

this is the saml authnrequest

`<?xml version='1.0' encoding='UTF-8'?>
<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" AssertionConsumerServiceURL="https:/XXXXXXXXXXXXXXXXXXXx" Destination="https://auth.my-numii.io/sso/post" ForceAuthn="false" ID="a114ce90gdg6h2ff1beie36g2jjffj7" IsPassive="false" IssueInstant="2018-06-28T07:30:43.296Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><ns1:Issuer>https://sso.online.tableau.com/public/sp/metadata?alias=ea962d84-5953-435d-a6db-71090a3b3e25</ns1:Issuer><ns2:Signature><ns2:SignedInfo><ns2:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><ns2:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" /><ns2:Reference URI="#a114ce90gdg6h2ff1beie36g2jjffj7"><ns2:Transforms><ns2:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><ns2:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></ns2:Transforms><ns2:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" /><ns2:DigestValue>mb4DBX4olvq8tZFtq+zMgSOcBLPjNxi+VbLCyKsaH20=</ns2:DigestValue></ns2:Reference></ns2:SignedInfo><ns2:SignatureValue>T4AK7DNDJ4pMrXB8ndmzXtvyN6RM7sjuAQ9q9l6l4+0P7mdw3JZ3TQKjB9sgwDEwb9Y4ILOrxjELUWLTV7kSXFai8a+E6j241Djmqw+LgzvLXBKFLgamVeizise78cE9WWjZonSOc0MNPYUyTdognFAlREasKkV6Rv6j4wkHu98=</ns2:SignatureValue><ns2:KeyInfo><ns2:X509Data><ns2:X509Certificate>MIICozCCAgygAwIBAgIGAWQ15g7DMA0GCSqGSIb3DQEBCwUAMGwxOzA5BgNVBAsMMmNvbS50YWJs
ZWF1c29mdHdhcmUuc2l0ZXNhbWwuY29yZS51dGlsLkNyeXB0b1V0aWxzMS0wKwYDVQQDDCRlYTk2
MmQ4NC01OTUzLTQzNWQtYTZkYi03MTA5MGEzYjNlMjUwHhcNMTgwNjI0MDc0MzQ2WhcNMjgwNjI1
MDc0MzQ2WjBsMTswOQYDVQQLDDJjb20udGFibGVhdXNvZnR3YXJlLnNpdGVzYW1sLmNvcmUudXRp
bC5DcnlwdG9VdGlsczEtMCsGA1UEAwwkZWE5NjJkODQtNTk1My00MzVkLWE2ZGItNzEwOTBhM2Iz
ZTI1MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDOrUrIzIyKD6hTQBWdxLVtztLXlQIgvEXp
ICdpuSVGZKga+zxcxB9s0qiDN4nYaS9MAYCxnZDO8aiM2Kx5VPygpyv0Vmh/9Ryq61BCEAuVgjNP
OvN158Qw3yGE3pPaGXkPLjCFc6kpdcKakjTB/kHpyZPRRpDnu6xYemO0fEWq/wIDAQABo1AwTjAM
BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBS9YsmNneD8YD3mhYNHs42pQ3MQ9jAfBgNVHSMEGDAWgBS9
YsmNneD8YD3mhYNHs42pQ3MQ9jANBgkqhkiG9w0BAQsFAAOBgQANA3+/sAu7pxI2lmRVDNiiA8wK
YfFuVImZXe1+12priFeOVJuwKCMTfUXPM0rZ+Ktl803uBFPhpnzWCd25vnU/PgMEyISGNw72wzt4
az7z1O7PlLDEPjGCHCE/aHv/HNnJAMKK+hzJ9XPBgk2wLFixa3YOAbZ2FPQ1gurNBfJaiA==</ns2:X509Certificate></ns2:X509Data></ns2:KeyInfo></ns2:Signature></ns0:AuthnRequest>
`

**Comment by peppelinux** [comment]
Try to disable signing in config['sp']

````
            'want_response_signed': False,
            'want_assertions_signed': False,
````

then your IDP must refetch the SP metadata, these also contains the previous entities to be requested to.

**Comment by skapin** [comment]
@peppelinux my IDP is pysaml2, my SP i s external and i cant modify it.
how can I acheive what you tell me ? (the SP provide me a XML file. I link this file on the IDP in the `"metadata": {
        "local": [full_path("../sp.xml")],
    },`
section.

I think you are write, it's someting going wrong somewhere but I cant find anything to help me and where start or how to try

**Comment by peppelinux** [comment]
Refetch sp metadata. SP gives you a metadata but later changed its configuration and the way to do saml requests to your idp

**Comment by Murajima** [comment]
I do not understand your answer here, what should i do?
I'm encountering almost the same problem as @skapin  and can't afford to resolve it either.
I do not have any access to my SP aswell, so i do not see how i can change the SP metadata, since i do not own it.

**Comment by peppelinux** [comment]
You should have just to download again your sp metadata, not modify it

**Comment by peppelinux** [comment]
I think that this issues doesn't exist and hopefully you've found a solution that fit your needs.
If a pysaml2 have in its metadata WantAssertionSigned and the IdP does not, this means that the IdP doesn't follow the specs or have a weak implementation of SAML2.

Hope that's this is a good time to close it definitively, tell me if you need to keep this open as reference, I will.
