### ISSUE TITLE
parse_authn_request_response errors when NameID is missing

### ISSUE THREAD

**Issue by ManThursday** [IdentityPython/pysaml2#522]
## Code Version
4.5.0

## Expected Behavior
The response should be parsed successfully.

## Current Behavior
```
  File "/Users/williamholloway/amplitude/.env/lib/python2.7/site-packages/saml2/client_base.py", line 717, in parse_authn_request_response
    self.users.add_information_about_person(resp.session_info())
  File "/Users/williamholloway/amplitude/.env/lib/python2.7/site-packages/saml2/population.py", line 27, in add_information_about_person
    session_info["not_on_or_after"])
  File "/Users/williamholloway/amplitude/.env/lib/python2.7/site-packages/saml2/cache.py", line 120, in set
    info['name_id'] = code(name_id)
  File "/Users/williamholloway/amplitude/.env/lib/python2.7/site-packages/saml2/ident.py", line 42, in code
    val = getattr(item, attr)
AttributeError: 'NoneType' object has no attribute 'name_qualifier'
```

`Cache` seems to rely on name_id existing but it only checks if the key is in the `session_info`.

## Possible Solution
Locally I tried changing `set` to return early `if name_id is None`. That seemed to fix it for my usage but I don't know if could have adverse effects on other functionality.

I was actually pretty surprised to see that pysaml2 was storing data like this.  Could someone give a little bit of context for why `Population` exists and what it's used for?

## Steps to Reproduce

1. Configure a pysaml2 client as an SP.
2. Call `parse_authn_request_response` with a response that is missing the `NameID` from the `Subject`.

**Comment by ambsw-technology** [comment]
If you want to implement a feature like Single LogOut, you need to know extra information about the user. At minimum, you need the NameID -- even if it's not what you use internally as a username (examples [here](https://www.samltool.com/generic_slo_req.php)).  I'm not sure about the rest, but it may be required for backchannel communications like Artifact Resolution Services.

**Comment by ManThursday** [comment]
I think (it was a while ago) that my concern was the manner in which the parsing fails.

It looks like whether or not NameID is actually required is a bit fuzzy https://github.com/onelogin/python-saml/issues/112

But if it is going to be treated as required then it should probably be asserted explicitly rather than just throwing an attribute error.

I think I ended up "fixing" this in my usage by passing a custom class to the `identity_cache` argument that drops all the user info rather than caching it which just avoids trying to read the NameID at that part of the code.

**Comment by JeroenvO** [comment]
Similar as https://github.com/IdentityPython/pysaml2/issues/620

**Comment by ambsw-technology** [comment]
Yes we also had to expicitly provide a cache since the NameID wasn't getting persisted by the package we were using.  See #646 for some discussion and examples of our wrapper class to leverage Djanog's caching infrastructure.

**Comment by peppelinux** [comment]
Persistence is something that need to be wrapped in each project. AFAIK pysaml2 doesn't have any persistence mechanism for a scalable and production ready environment. in djangosaml2 and uniauth I handled with my own. If a scalable storage layer woudn't be released in future I sincerely suggest to set aside pysaml2 storage and rely on your tools

**Comment by peppelinux** [comment]
Going to close it but I think that's important to follow for future releases.
Moving this topic here:
https://github.com/IdentityPython/pysaml2/issues/522#issuecomment-687674080

I Hope to make some order to work better and all together for the next releases
