### ISSUE TITLE
s2repoze plugin implements IChallenger in the incorrect way

### ISSUE THREAD

**Issue by maciekwisniewski** [IdentityPython/pysaml2#523]
I've integrated pysaml2 with my app that uses who.repoze and I found an issue with single log out initiated by IDP. At the end of the process client.handle_logout_request returns me a piece of HTML that should be POSTed by the browser to IDP and the sp plugin in sp.identify puts it in environ['samlsp.pending'].

This is then taken out by sp.challenge that is called by who.repoze and returned directly as a list of strings where each string is a line of that HTML.

However according to the documentation http://repoze.readthedocs.io/projects/repozewho/en/latest/plugins.html#writing-a-challenger-plugin it expects a callable object, so I am getting error in my logs:

File "/usr/local/lib/python2.7/site-packages/repoze/who/middleware.py", line 110, in __call__
    app_iter = challenge_app(environ, start_response)
TypeError: 'list' object is not callable

In some other cases our plugin works correct, it returns a callable object, eg:

            if not ht_args["data"] and ht_args["headers"][0][0] == "Location":
                logger.debug('redirect to: %s', ht_args["headers"][0][1])
                return HTTPSeeOther(headers=ht_args["headers"])
            else:
                return ht_args["data"]

as HTTPSeeOther is accepted by repoze.who but just a list of strings is not.

The middleware.py fragment using the above returned value looks like that:

            challenge_app = api.challenge(wrapper.status, wrapper.headers)
            if challenge_app is not None:
                logger and logger.info('executing challenge app')
                if app_iter:
                    list(app_iter) # unwind the original app iterator
                # PEP 333 requires that we call the original iterator's
                # 'close' method, if it exists, before releasing it.
                close()
                # replace the downstream app with the challenge app
                app_iter = challenge_app(environ, start_response)

So it is a problem on pysaml2 repoze.who plugin that it sometimes returns just the plain HTML as a list of lines instead of something that can be called in the last line of above code.

How to wrap the HTML generated by client.handle_logout_request into a callable PEP 333 app?

**Comment by peppelinux** [comment]
I think that there some kind of I/O badness in your implementation. I dind't use your tools so I don't have any useful example to face this.

Please reply to this with additional info, this thread will be closed in weeks otherwise
thank you for sharing
