### ISSUE TITLE
Allow mulitiple id_attr_name pass through to xmlsec1

### ISSUE THREAD

**Issue by pbuckner** [IdentityPython/pysaml2#552]
metadata config adds attribute value `id_attr_name`, which is passed through to sigver.py where it adds to the command line call to xmlsec1.
    `   xmlsec1 --id-attr:{id_attr} <node_name>`

xmlsec1 allows multiple iterations of this parameter on the command line, for example
` xmlsec1 --decrypt --id-attr:Id EncryptedKey --id-attr:ID EncryptedKey ...`

Which would allow decryption using either `Id` or `ID` to be used.

Request is to allow metadata config parameter `id_attr_name` to be (optionally) a list. In sigver.py, choose the 1st value of list when encrypting. Use all values in the list when decrypting

## Code Version

4.6.3
## Expected Behavior

Allow setting of `id_attr_name` in metadata config to be either (current) single value string, or list of strings.

Within sigver.py, CryptoBackendXmlSec1.decrypt()
create list of `--id-attr:{id_attr} ENC_KEY_CLASS` command line parameters, one for each value of id_attr

Within sigver.py CryptoBackendXmlSec1.sign_statement()
use only first value of id_attr to pass to xmlsec1 command

Within sigver.py CryptoBackendXmlSec1.validate_signature()
Same as decrypt() -- create multiple command line options

## Current Behavior

Current behavior requires id_attr_name to be single value string

## Possible Solution

Some IdP use 'Id', some use 'ID', setting id_attr_name to single value will work for some, but not all IdP (pysaml fails to parse Encrypted Assertions from okta IdP, for example)

Fix is backward compatible, and limited to sigver.py

```diff
    def decrypt(self, enctext, key_file, id_attr):
        ...
+       id_attr = id_attr if isinstance(id_attr, (list, tuple)) else [id_attr, ]
+       attrs = [('--id-attr:{id_attr}'.format(id_attr=x), ENC_KEY_CLASS) for x in id_attr]
        com_list = [
            self.xmlsec,
            --decrypt',
            --privkey-pem', key_file,
        ]
+       [com_list.extend(x) for x in attrs]
        ...

    def sign_statement(...):
        ...
+       id_attr = id_attr[0] if isinstance(id_attr, (list, tuple)) else id_attr
        ...

    def validate_signature(...):
        ...
+       id_attr = id_attr if isinstance(id_attr, (list, tuple)) else [id_attr, ]
+       attrs = [('--id_attr:{id_attr}'.format(id_attr=x), node_name) for x in id_attr]
        com_list = [
            self.xmlsec,
            '--verify',
            '--enabled-reference-uris', 'empty,same-doc',
            '--pubkey-cert-{type}'.format(type=cert_type), cert_file,
        ]
+       [com_list.extend(x) for x in attrs]
        ...
```

## Steps to Reproduce

Not a bug.

**Comment by sheilatron** [comment]
[This PR](https://github.com/IdentityPython/pysaml2/pull/612) is an attempt to address the decryption part of the issue. It has worked for me when testing with different IdPs which encrypt using variant cases of id-attr.

**Comment by peppelinux** [comment]
Fixed here:
https://github.com/IdentityPython/pysaml2/pull/662

job done, thank you all for this
