### ISSUE TITLE
Testing on Google App Engine and receiving error on cryptography dependency

### ISSUE THREAD

**Issue by EChu16** [IdentityPython/pysaml2#554]
I've been attempting to run Pysaml2 on my Google AppEngine project and have installed pysaml2 via pip. However, when I try to execute a simple import such as `from saml2.client import Saml2Client`, I receive `ImportError: No module named cryptography.hazmat.bindings._constant_time`

## Code Version

I'm running the latest version of pysaml2 and have updated OpenSSL and cryptography dependencies.
## Current Behavior

The error trace I get is this:
```
File "<string>", line 9, in <module>
  File "/3p/saml2/client.py", line 9, in <module>
    from saml2.request import LogoutRequest
  File "/3p/saml2/request.py", line 9, in <module>
    from saml2.response import IncorrectlySigned
  File "/3p/saml2/response.py", line 47, in <module>
    from saml2.sigver import security_context
  File "/3p/saml2/sigver.py", line 4, in <module>
    from OpenSSL import crypto
  File "/3p/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/3p/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/3p/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/3p/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/3p/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/3p/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
  File "/3p/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 1095, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named cryptography.hazmat.bindings._constant_time
```

## Possible Solution

I am aware that Google App Engine requires that all 3rd party libraries use pure Python code with no C extensions and I believe from what I read, Pysaml2 is fit this criteria. However, since it uses pyOpenSSL and that requires .so imports, does this mean this isn't compatible with GAE or did I mess something up during installation?

**Comment by c00kiemon5ter** [comment]
> However, since it uses pyOpenSSL and that requires .so imports, does this mean this isn't compatible with GAE

It seems [that is the case](https://github.com/pyca/cryptography/issues/2764). I had no idea that GAE had such restrictions but it seems those [are gone with python-3.7](https://cloud.google.com/appengine/docs/standard/python3/python-differences#restrictions)

> #### Third party dependencies and native code
> [using python 3.7] You can install arbitrary third party dependencies, including those that use native code

**Comment by c00kiemon5ter** [comment]
I do not think there will be work put into this (and supporting python2 in general). I am closing this.
