### ISSUE TITLE
SamlBase and its descendants shold be moved to own package

### ISSUE THREAD

**Issue by erakli** [IdentityPython/pysaml2#568]
Because SamlBase and company represent XML and work something like ElementTree, we should move it to separate package, for instance `saml2.xml`

**Comment by c00kiemon5ter** [comment]
I agree that `SamlBase` and other classes that represent saml-entities should be on its own package. But that is not relevant to xml. XML is just a representation; there is nothing stopping you from representing SAML message with JSON (or other better data formats). So, these classes are the core of the domain, where the domain is ofcourse SAML. The classes should be decoupled from their data representation (_your data model is not your object model is not your resource model is not your message model_). Manipulation of the data should be done through the `saml2.xml` but the classes themselves should be in a package like `saml2.core` (or even align the package names with the specs).
Keep in mind that the main reason development is moving slowly is backwards compatibility.

**Comment by erakli** [comment]
Totally agree. I was incorrect about XML. Of course, there's talk about SAML entities. 

Are you sure, that `pysaml2` needs backward compatibility in new major versions? For instance, in ver. 5? 

Also, these entities could be moved into own module (`saml2.core` sounds cool) and then, imported as a shortcut in main __init__.py file. This preserve compatibility and make repo structure clearer. 

And what about to discard support of python 2.7 in next major version and concentrate on Python 3.6+?

**Comment by c00kiemon5ter** [comment]
Moving modules around is the easy part (some attention needs to be given to not create dependency cycles). The hard part is giving clear responsibilities to modules and decoupling components.

Dropping python2 support is big subject deserving its own thread. I would _really like_ to only deal with python3, but there are still systems that come with python2 by default, and systems that use the pysaml2 through python2 projects. Feel free to join [the idpy list](https://lists.sunet.se/listinfo/idpy-discuss) and make a proposal ;)

**Comment by erakli** [comment]
About decoupling and other stuff: it's hard but not impossible task. There's need to define tasks that needed to be accomplished and do extensive code review on this changes. 

About python3: I agree, it's big topic and I'll take look at this mailing list. My vision is that while there's still systems that dependent on support of py2, we can simply create branch with current version and make minor updates in it, while development version will take actions on migrating to py3. And then, development version will become pysaml2 v.5, with support for py3 only. 

If systems need to be deployed with py2, then they can simply stick themselves to pysaml2 v. 4
