### ISSUE TITLE
Help in running examples

### ISSUE THREAD

**Issue by dante1119** [IdentityPython/pysaml2#569]
Help for running example

## Code Version
pysaml2 4.6.3 on centos 7 python 3.5

## Expected Behavior
I should access the SP page after authentication on Idp 

## Current Behavior
I get an emtpy page and the log shows:
"ValueError: WSGI Applications must yield bytes"

## Possible Solution
I did try to find a fix for UTF encoding in wsgi.py , but it is not clear

## Steps to Reproduce
1.Just run the example as specified in relative README.rst

Thankyou for any help

**Comment by c00kiemon5ter** [comment]
Thanks for reporting this. #566 has already addressed this issue and will be in the next release that will come out today ;)

**Comment by tsuki-yama** [comment]
Example project not working properly.
Everything is the same.

**Environment tools:**
pysaml 4.6.5, ubuntu 18.4, python 3.6.7

**Comment by c00kiemon5ter** [comment]
Examples should be fixed by 2dc351e65ee0637ddc242c9eff128a28aa4f6f6c

**Comment by telemmaite** [comment]
Hitting **/metdata** returns same error for **sp-wsgi** example.

**Comment by c00kiemon5ter** [comment]
@telemmaite should be fixed by f41f60c
