### ISSUE TITLE
No exception for StatusError

### ISSUE THREAD

**Issue by tpazderka** [IdentityPython/pysaml2#571]
## Code Version

4.6.4
## Expected Behavior

If client is parsing a message with error status (for example  status code `urn:oasis:names:tc:SAML:2.0:status:UnknownPrincipal`), an exception should  be raised.
## Current Behavior

No exception is raised and a `response` object is returned from `Base.parse_authn_request_response` with no easy way of detecting the error type/message.
## Possible Solution

This has been caused by catching an Exception [here](https://github.com/IdentityPython/pysaml2/blob/v4.6.4/src/saml2/entity.py#L1210) and not propagating it further.
## Steps to Reproduce

1. Create an XML message with error status and status code of `urn:oasis:names:tc:SAML:2.0:status:UnknownPrincipal`
2. Parse the message with the client

**Comment by rectalogic** [comment]
This worked in v4.6.3
