### ISSUE TITLE
Azure AD sends SAMLResponse without NameFormat property

### ISSUE THREAD

**Issue by dbasilio** [IdentityPython/pysaml2#584]
One of our clients is implementing Azure AD as their IDP and our integration started failing. Azure AD does not send the NameFormat property, and they seem to have no intention of adding this ability, as seen [here](https://social.msdn.microsoft.com/Forums/en-US/9fafe20e-53c2-4b5b-8879-7170b0c2c186/provide-the-ability-to-define-nameformat-for-attributes-in-saml-assertions?forum=WindowsAzureAD).

Without NameFormat, pysaml2 defaults to `urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified` which might be fine, but for our use case does not work. Looking at how IBM manages [Attribute Mapping](https://www.ibm.com/support/knowledgecenter/en/SSCT62/com.ibm.iamservice.doc/tasks/t_attributes_mapping.html), they default to basic instead of to unspecified.

In pysaml2, the unspecified attribute maps are all for ADFS, and seems to be very limited whereas the basic attribute map has a ton of properties.

## Code Version
We run 2.0.0 and 4.6.3 depending on the client, but I confirmed this issue still exists in 4.6.5.

## Possible Solution
I think the default 'should' be basic, but if that's too big a risk to take on, I think allowing consumers to define their own default attribute mapping is a good idea. This way consumers that never use unspecified attribute mapping can default to basic instead.

**Comment by dbasilio** [comment]
I know this is similar to https://github.com/IdentityPython/pysaml2/issues/466 but that deals with the request as opposed to the response, and this is specific to Azure AD so I thought it made sense as a separate issue.

**Comment by c00kiemon5ter** [comment]
Hello, quoting [the specification](https://www.oasis-open.org/committees/download.php/56777/sstc-saml-core-errata-2.0-wd-07-diff.pdf):

> #### `NameFormat` [Optional]
> A URI reference representing the classification of the attribute name for purposes of interpreting the name. See Section §8.2 for some URI references that MAY be used as the value of the `NameFormat` attribute and their associated descriptions and processing rules. **If no NameFormat value is provided, the identifier `urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified` (see Section §8.2.1) is in effect**.

This is why the default is that. However, I am not sure what you're trying to achieve.

attributemaps will be going away in the future (see #549). Until then, you can define and use your own maps, provided you configure [`attribute_maps_dir` option](https://github.com/IdentityPython/pysaml2/blob/master/docs/howto/config.rst#attribute-map-dir). Copy the ones we ship (if you need them) and create or amend with the ones you need.

**Comment by dbasilio** [comment]
How often are the attribute maps you ship updated? My concern with copying the attribute maps locally is that there would be updates in pysaml2 that we would not notice and then fall out of date.

**Comment by c00kiemon5ter** [comment]
About once or twice every year. You can also automate the process of copying and amending the maps with your own entries, so that you always use the latest version.
The intent is to stop using those maps. Having said this, it should be safe to go with that option.
