### ISSUE TITLE
[Additional Features] Attribute rewrite and transformation on the fly

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/pysaml2#587]
## Code Version
master branch

## Expected Behavior
I'd like to know if there's a way to aggregate or rewrite, transform or create, an attribute value before transmitting it to an SP, as Shibboleth IDP already does. Shibboleth SP can also do an AttributeResolver type=Transform to do this kind of things. I think that could be usefull to discuss about this feature if you agree. 

Some of these use cases are here:
- [IDP AttributeResolver](https://github.com/ConsortiumGARR/idem-tutorials/blob/master/idem-fedops/HOWTO-Shibboleth/Solutions/HOWTO%20Define%20dynamically%20attributes%20for%20Shibboleth%20IdP%20v3.md)
- [SP AttributeResolver](https://github.com/peppelinux/idem-tutorials/blob/master/idem-fedops/HOWTO-Shibboleth/Solutions/HOWTO%20Transform%20and%20add%20attributes%20dynamically%20for%20Shibboleth%20SP2%20and%20SP3.md)

## Current Behavior
At this time, following pySAML2 docs, I read about attribute policy but nothing about attribute transformation (or creation default ones).

## Possible Solution
Would you like to spend some thoughts on it?

**Comment by peppelinux** [comment]
Regarding pySAML2, together with attributes_restrinctions, I thought that something like "attributes_(processing | postprocessing | rewrite)" could also be great... Following Shibboleth examples.

In production use often we need to suggest to SP admins some way to transform attribute for retrocompatibility, other times we need to do this IDP side.

I get it.
I'd also like to see some examples about attributes transformation in SATOSA, if there's someone over there.

**Comment by c00kiemon5ter** [comment]
I think we could have that as part of the policy, as you suggest. A simple mechanism to modify the attributes. I will think about it more.
Let me be clear, that this is certainly not a priority - we have many things to fix at the moment, which are more important than a new feature.

**Comment by c00kiemon5ter** [comment]
SATOSA has an internal representation (a dictionary) of the attributes. Plugins interact with this representation and add/remove/modify attributes. Then the dictionary is converted back to actual attributes - below is a call chain of the process (I've skipped some intermediate calls):

https://github.com/IdentityPython/SATOSA/blob/0312313a1892b/src/satosa/frontends/saml2.py#L289-L290
https://github.com/IdentityPython/SATOSA/blob/0312313a1892b/src/satosa/frontends/saml2.py#L373
https://github.com/IdentityPython/pysaml2/blob/0312313a1892b/src/saml2/server.py#L323
https://github.com/IdentityPython/pysaml2/blob/0312313a1892b/src/saml2/assertion.py#L729

**Comment by peppelinux** [comment]
Glad to hear this, there's no hurry. We could open a separate branch to deal with this additional feature if you agree. I will spend just two words on this.

At this time we have a policy definition like this:
````
"attribute_restrictions":{
                     "mail": [".*\.umu\.se$"],
                }
````

I'd purpose to couple the policy with the rewrite rules, like this proof:
````
from attribute_rewrites_functions import (remove_mace_urn, 
                                                                 compose_eppn_from_homeorg,
                                                                 compose_display_name)

[....]

"attribute_rewrite_func":{
                     "displayName": [compose_display_name,]
                     "eppn": [compose_eppn_from_homeorg,],
                     "shacpersonaluniqueID": [remove_mace_urn,]
                }
````

Every rewrite functions will get all the attributes  as arguments, because a rewrite function could need two or more attributes to forge a new one. For example: compose_display_name could need cn and sn and return ' '.join((cn, sn)), compose_eppn_from_homeorg could return '@'.join((uid, SchacHomeOrganization)). Appending more rewrite functions in a chain, a list, could let us to compose more complex and quite generalized rewrites.

To handle these rewrite definitions we could think to add a method called "apply_rewrites" after apply_policy:
https://github.com/IdentityPython/pysaml2/blob/711565f/src/saml2/assertion.py#L810

In general I'd like to mantain policy and rewrites in two separate methods and definition in idp configuration. The rewrites rules should also be applied in a SP configuration if you agree.

**Comment by peppelinux** [comment]
Probably the correct place to do this is in saml2.attribute_converter.AttributeConverter

**Comment by peppelinux** [comment]
@c00kiemon5ter If I develop this feature is there any possibilities to integrate this into pysaml official branch, following the community-dev guideline, or it would be better to leave this topic off?

I'd need this kind of feature because I'd prefer to handle this directly in pysaml2, instead of develop the same feature separately, as a middleware, in my sp and idp. Your opinion is important, any suggestion will be considered

**Comment by peppelinux** [comment]
Implemented outside of pysaml2, good enough

**Comment by artooro** [comment]
Can we re-open this issue? I am wanting to be able to do the same thing. Two different scenarios.

1. IDP offers first name and last name attributes, but the SP only uses a single name attribute. I'd like to write a function to combine the two names into one.

2. IDP offers email address as the only unique identifier, I want to strip the @domain.com part of the attribute for the SP.

I've been searching for a way to do this in pysaml2 as it's being used in the Synapse server.

**Comment by peppelinux** [comment]
I'm having fun with this kind of approach
https://github.com/peppelinux/pyMultiLDAP/blob/master/examples/settings.py.example#L62

I'll adopt It also in uniAuth
https://github.com/UniversitaDellaCalabria/uniAuth/issues/17

**Comment by peppelinux** [comment]
I think this topic has now been properly addressed. pysaml2 confirms its position as a base library and this function is therefore delegated to the wrappers above it. Thank you all for enriching and stimulating this thread
