### ISSUE TITLE
NameIDFormat AllowCreate default should be true

### ISSUE THREAD

**Issue by mrvanes** [IdentityPython/pysaml2#589]
We can configure AllowCreate NameIDFormat but, it turns out, the unconfigured default is false. This is against the SAML2int specs as can be read here: https://saml2int.org/profile/current/
```
The <saml2p:AuthnRequest> message SHOULD contain a <saml2p:NameIDPolicy>
element with an AllowCreate attribute of "true". 
```

**Comment by mrvanes** [comment]
https://github.com/IdentityPython/pysaml2/pull/590

**Comment by c00kiemon5ter** [comment]
Quoting the [SAML2 core specification](https://www.oasis-open.org/committees/download.php/56776/sstc-saml-core-errata-2.0-wd-07.pdf) (Page 53 of 93):
> ## 3.4.1.1 Element `<NameIDPolicy>`
> [...]
> #### AllowCreate [Optional]
> A Boolean value used to indicate whether [E14]the requester grants to the identity provider, in the course of fulfilling the request, permission to create a new identifier or to associate an existing identifier representing the principal with the relying party. **Defaults to "false"**. 

This is why the default is `false`. There is no assumed _profile_ implemented by pysaml2, but the specification. SAML profiles may specify the intended behaviour when setting this value to `true`, and I guess that's what SAML2int does.

I think the default should stay as it is. The configuration option is there to use; though, I think it remains undocumented. Changing the default now, would also result in a breaking change.

What would be nice to implement is a configuration option to enable support for a specific profile. Setting that would automatically check, set and warn for this kind of options as required by that profile.  This is how the `SAMLEIDASBackend` works for SATOSA, but this could also be implemented in pysaml2 and maybe done in a pluggable way, so others can extend this without the need to be part of pysaml2.

**Comment by mrvanes** [comment]
Fair enough, the reason for raising the issue is heavy head bangng while deploying satosa in a saml2int environment recently :/
