### ISSUE TITLE
Installing without Paste?

### ISSUE THREAD

**Issue by rnd0101** [IdentityPython/pysaml2#591]
## Code Version
latest release

## Expected Behavior
When installing pysaml2 I expect only core dependencies to be installed.

pip install pysaml2

I do not believe Paste is needed for many (most?) cases of pysaml2, maybe I am wrong?

## Current Behavior
Paste, repoze.who, etc (from require_extras)

## Possible Solution
Not quite sure: can't find a way to say NOT to install some extras in requirements.txt file

## Steps to Reproduce

1. create new virtual env
2. pip install pysaml2==4.0.3
3. pip freeze
4. Extras are there (eg Paste)

**Comment by c00kiemon5ter** [comment]
Hello, by the step you posted, you are using version `4.0.3`. Latest version is `4.6.5`. Please, switch to a newer version and what you're seeing should go away. Installing the latest version in a clean environment you should get an output similar to the following:

```
$ pip freeze
asn1crypto==0.24.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.5
defusedxml==0.5.0
enum34==1.1.6
future==0.17.1
idna==2.8
ipaddress==1.0.22
pycparser==2.19
pyOpenSSL==19.0.0
pysaml2==4.6.5
python-dateutil==2.8.0
pytz==2018.9
requests==2.21.0
six==1.12.0
urllib3==1.24.1
```
