### ISSUE TITLE
Do not trust the certificate contained in the SAML Response

### ISSUE THREAD

**Issue by jkakavas** [IdentityPython/pysaml2#594]
## Code Version
4.6.5

## Expected Behavior
The certificate that is contained in the signature of the SAML message ( in `<ds:KeyInfo><ds:X509Data><ds:X509Certificate>`) should match an explicitly configured one in IDPs metadata before it is used. It should be used only as an indication of the public key to use for signature verification in case of multiple supported keys, and not as the source of the public key for verification. 

## Current Behavior
In a malformed configuration were `metadata` is `None`, or using a malformed IDP metadata file where no key with `use=signing` is configured the certificate that is contained in the SAML message is used as the source of the public key material for signature verification. 
This is further affected by the default value of `only_use_keys_in_metadata` being `False`. 

## Possible Solution
- Set the default value of `only_use_keys_in_metadata` to a sane default (`True`)
- Rework the verification logic to use the included certificate as a pointer to an already trusted key, instead of a trusted key itself

**Comment by peppelinux** [comment]
I think that's should be moved ASAP in the official documentation, following also this thread
https://github.com/IdentityPython/pysaml2/issues/706

**Comment by peppelinux** [comment]
@ivan if you agree we Just have to set default value of only_use_keys_in_metadata True and put a note in the documentation for the next release, thenmoving closing this

**Comment by peppelinux** [comment]
At this moment only_use_keys in metadata is True by default.
https://github.com/IdentityPython/pysaml2/blob/1aeae3ae565e02f863a26b2893354d048a7abff8/src/saml2/config.py#L217

Going to close this, thank you for all
