### ISSUE TITLE
[BUG in example sp/idp] SLO: 'str' object has no attribute 'c_namespace'

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/pysaml2#595]
The Exception `'str' object has no attribute 'c_namespace'` throws in the web page, without let the users logout.

Python 3.5.2 (Ubuntu 16.04)

## Code Version
master branch

## Expected Behavior
Logout without exceptions

## Steps to Reproduce
Execute the test in example folder: `./all.sh start`
Login as `roland` `dianakra`, then logout

**Comment by peppelinux** [comment]
It throws here:
````
saml2/entity.py(239)apply_binding()
-> info = self.use_soap(msg_str, destination, sign=sign, **kwargs)
````
from
````
saml2/httpbase.py(354)use_soap()
            _signed = self.sec.sign_statement(soap_message,
                                              class_name=class_name(request),
                                              node_id=request.id)
````
the problem is that request is passed as a  string object, and it don't have any c_namespace and c_tag.
````
def class_name(instance):
    return "%s:%s" % (instance.c_namespace, instance.c_tag)
````
By the way the real problem is that request in the example is not signed but it comes as it was signed.
Then the fix is to change , in sp_conf.py:

````
            "logout_requests_signed": False,
````
This way it work as espected. Is this good enough?

**Comment by peppelinux** [comment]
https://github.com/IdentityPython/pysaml2/issues/536

Probably this issue related to this problem

**Comment by peppelinux** [comment]
See: https://github.com/IdentityPython/pysaml2/issues/334#issuecomment-474407731

**Comment by peppelinux** [comment]
AFAIK this kind of problem happened because of a faulty configuration between the SP and IdP in my test environment. Closing this, we just have some help to keep an eye for other issue attributable to this.

**Comment by omizrahi99** [comment]
I am getting this exact issue when logging out using the examples. I tried applying `"logout_requests_signed": False` in the `sp_conf.py` file and creating new metadata using the new config but I still get `'str' object has no attribute 'c_namespace'` when logging out.

**Comment by FranciscoSP** [comment]
> I am getting this exact issue when logging out using the examples. I tried applying `"logout_requests_signed": False` in the `sp_conf.py` file and creating new metadata using the new config but I still get `'str' object has no attribute 'c_namespace'` when logging out.

Same here. It seems that the "sign" parameter is not being sent to "sp.global_logout". So I made the following in the "sp.py" file at the "logout" function.

```
    CONFIG = importlib.import_module(CNFBASE).CONFIG
    data = sp.global_logout(user.name_id, sign=CONFIG["service"]["sp"]["logout_requests_signed"])
```

It solved my problem.

**Comment by c00kiemon5ter** [comment]
Hello,

please, if you can verify with the latest HEAD (8f3b407) that'd be great.
The changeset fixes how `sign*` flags are derived in order to create a request of the proper type.
That should fix the `'str' object has no attribute 'c_namespace'` (also, on the examples).

On a related note #793 fixes how `logout_requests_signed` configuration is processed
and should now be properly respected.
