### ISSUE TITLE
[Documentation proposal] Running test and code linting

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/pysaml2#596]
I runned the tests in the current master branch.
I propose to add a requirements file because I had to install the following dependencies to get test running:

````
pip install pymongo mock responses
````
I also have to report my result:
`6 failed, 666 passed, 3 skipped, 744 warnings in 50.99 seconds`

About the code linting with flake8, I got 4163 alerts. I also didn't find any flake init file.

**Comment by c00kiemon5ter** [comment]
Hi @peppelinux 

The `tests/` folder contains [`test-requirements.txt`](https://github.com/IdentityPython/pysaml2/blob/master/tests/test-requirements.txt).

Tests run on every PR and commit on travis-ci. See the [travis](https://github.com/IdentityPython/pysaml2/blob/master/.travis.yml) and [tox](https://github.com/IdentityPython/pysaml2/blob/master/tox.ini) configurations.

Regarding flake8, it is not as easy as it seems. We cannot just go through the whole codebase and change the formatting. It has to be done incrementally.
You can see some flake8-specific options in [config.cfg](https://github.com/IdentityPython/pysaml2/blob/master/setup.cfg#L83)

**Comment by peppelinux** [comment]
Thank you very much
