### ISSUE TITLE
Feature Request: For IDP, use a custom template for HTTP form post

### ISSUE THREAD

**Issue by lindycoder** [IdentityPython/pysaml2#600]
Hi, thank you for your tool!

When server's `apply_bindings()` handles an `BINDING_HTTP_POST` it ultimately uses `https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/pack.py#L43` as a template for the form.

Would be great to personalize this page for users to see something while they wait.
> Why do they wait, it's an auto post! you say?

Well if the place where you post takes some time do to stuff, the users sits on a white page loading.  Also if javascript is deactivated, the look is very basic.

## Code Version
pysaml2==4.6.5 (irrelevant i think)

## Expected Behavior
Have a way to customize the template

## Current Behavior
Needs to monkey patch the code or use alternate path for HTTP_POST

## Possible Solution
An optional template, in the .format() form, fed into the IDP config

## Steps to Reproduce
N/A

**Comment by peppelinux** [comment]
Hi @lindycoder, you can always handle the authn response as you prefer, watch this for example:
https://github.com/peppelinux/djangosaml2idp/blob/master/djangosaml2idp/views.py#L205

It takes `(request, binding,authn_resp, destination, relay_state)` as arguments to render these in a custom template. Apply binding sound more like a shortcut to handle in a single shot differents bindings like redirect and post. 

This is only an example, you can do as you prefer

**Comment by lindycoder** [comment]
All right fair enough i can work that, thank you
