### ISSUE TITLE
validate  idp x509 cert

### ISSUE THREAD

**Issue by bifiar** [IdentityPython/pysaml2#604]
i am using pysaml2 for the SP side and Okta for IDP , OKTA requires now to validate the SAML 2.0 request/response with x509 public certificate
that they providing. what should I add to the settings? I found this guide:
https://medium.com/@gohberg/okta-authentication-using-saml-simplified-python-version-74ea9d5b4be7
but it only refers to pysaml 3 ...
can someone help, please?

**Comment by abliqo** [comment]
How does the SAML response look like from your IDP? What is the value of "method" attribute in the "SubjectConfirmation" tag of SAML response?

**Comment by peppelinux** [comment]
Closed for inactivity
