### ISSUE TITLE
SubjectConfirmation with method sender-vouches and without SubjectConfirmationData raises AttributeError

### ISSUE THREAD

**Issue by user37596** [IdentityPython/pysaml2#608]
Pysaml2 raises AttributeError when receiving a response with SubjectConfirmation with method "urn:oasis:names:tc:SAML:2.0:cm:sender-vouches" and the SubjectConfirmationData element is missing. AFAIK, the data is not required when using sender-vouches.

## Code Version
pysaml2==4.7.0

## Expected Behavior
Pysaml shouldn't require SubjectConfirmationData to exist when sender-vouches is used.

## Current Behavior

The variable _data in the below code (from AuthResponse.get_subject()) is None when no SubjectConfirmationData exists. The code crashes at the `_recip = _data.recipient` with AttributeError: None does not have attribute recipient.

```
        for subject_confirmation in subject.subject_confirmation:
            _data = subject_confirmation.subject_confirmation_data

            if subject_confirmation.method == SCM_BEARER:
                if not self._bearer_confirmed(_data):
                    continue
            elif subject_confirmation.method == SCM_HOLDER_OF_KEY:
                if not self._holder_of_key_confirmed(_data):
                    continue
            elif subject_confirmation.method == SCM_SENDER_VOUCHES:
                pass
            else:
                raise ValueError("Unknown subject confirmation method: %s" % (
                    subject_confirmation.method,))

            _recip = _data.recipient
            if not _recip or not self.verify_recipient(_recip):
                raise VerificationError("No valid recipient")

            subjconf.append(subject_confirmation)
```

## Possible Solution

We fixed the problem by copy-paste-overriding the get_subject in our own response class and modifying the sender-vouches elif part like this:

```
            elif subject_confirmation.method == SCM_SENDER_VOUCHES:
                subjconf.append(subject_confirmation)
                continue
```

Now the code works for us. Not sure if this is the right way to fix it in the pysaml2 package itself. I don't know if the SubjectConfirmationData should never be there with sender-vouches, or it could be there. Anyways, in our case we could safely assume it's not there.

## Steps to Reproduce

Don't know how to easily reproduce this locally, but here is the subject element we had the exception with.

```
<saml:Subject>
    <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">...</saml:NameID>
    <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:sender-vouches"/>
</saml:Subject>
```

**Comment by peppelinux** [comment]
Hi, can you reproduce this beahviour with the last pysaml2 release and also tell us how to reproduce it?
Thank you
