### ISSUE TITLE
Why are audience restrictions not checked by SP for unsolicited requests?

### ISSUE THREAD

**Issue by morty** [IdentityPython/pysaml2#609]
## Code Version

pysaml2==4.5.0

## Expected Behavior

We have multiple hosting environments for our website (which acts as an SP) that use different configurations in the IDP which have different entityids. When the SAML comes back it has the entityid in the `AudienceRestriction` section. To prevent SAML from one configuration being used against an environment with a different configuration the SP should check that the entityid matches. This should be done for both solicited and unsolicited.

## Current Behavior

The code currently checks that unsolicited responses are not allowed before doing the audience restriction check.

https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/response.py#L614

This means that if `allow_unsolicited` is set to `True` then for all SAML, solicited or not, the audience restriction check will not be done. Therefore request from a different profile with a different entityid can be replayed to gain acccess.

## Possible Solution

Remove the line where it checks if that unsolicited requests are not allowed before proceeding with the audience restriction check. 

https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/response.py#L614

**Comment by c00kiemon5ter** [comment]
Hm, I am not sure if there is an explanation for this. The [code introducing this check](https://github.com/IdentityPython/pysaml2/commit/82ee848213c17e30f31517a6ba458418a6b58058#diff-8eafba812bf2ea0433c2003370677b52) does not help much.
I stand by what you say; I think this check is wrong. What I can guess is, the author might have been confused about what unsolicited is about. I will go forward and remote that check.
