### ISSUE TITLE
name_id and session_index are None in response session_info

### ISSUE THREAD

**Issue by fboerman** [IdentityPython/pysaml2#620]
im making use of pysaml2 by using the excellent djangosaml2 library. However I have encountered some behaviour I do not understand. I have a client running talking to a saml identity provider

I have cut down the problem to the following:
create a cleant with Saml2Client and parse the response with parse_authn_request_response
this goes without errors

then I request the session_info with response.session_info() in which response is the returned object from the parse_authn_request_response

Most of the info in the resulting session_info are what I would expect, except for that name_id and session_index are both None. This causes problems further down in the djangosaml2 library. But the core problem is that the those two parameters are not put in the response object. I have a similar client setup which uses the same setup which does get these parameters filled (with the same Identity Provider) I am not sure what im doing wrong.

Why are the name_id and session_index not set?

**Comment by peppelinux** [comment]
Can you share this SP configuration?

When you get authn response from idp, in the xml response message Is there any of the missing values? If no: the idp do not release these. 

I use djangosaml2 too.
Configuring debug:true can you sede these values in the ava dictionary?

**Comment by ambsw-technology** [comment]
Are you using ADFS?  NameID is not provided by default and must be configured.

**Comment by JeroenvO** [comment]
Yes, this is a setup using ADFS, i'am a partner of @fboerman. Is there an option to configure this name-id client-side?
A sample log entry looks like this:
`DEBUG 2020-06-08 12:40:51,864 views.py:337 Trying to authenticate the user. Session info: {'ava': {'urn:mace:dir:attribute-def:displayName': ['<fullname>'], 'urn:mace:dir:attribute-def:givenName': ['Jeroen'], 'urn:mace:dir:attribute-def:mail': ['<email>'], 'urn:mace:dir:attribute-def:sn': ['Oorschot, van'], 'urn:mace:dir:attribute-def:uid': ['<username>'], 'Initials': ['J.J.'], 'NameID': ['<username>']}, 'name_id': None, 'came_from': '/', 'issuer': '<some uri>', 'not_on_or_after': 1591616451, 'authn_info': [('urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport', [], '2020-06-08T09:54:14.211Z')], 'session_index': None}
`
with some values replace with <>

**Comment by JeroenvO** [comment]
The corresponding saml attribute statement log entry as logged in `attribute_converter.py:680`
`
<saml:AttributeStatement xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="htt
p://www.w3.org/2001/XMLSchema-instance">
<saml:Attribute Name="urn:mace:dir:attribute-def:displayName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format
:uri">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string"><--fullname-->
    </saml:AttributeValue>
</saml:Attribute>
<saml:At
        tribute Name="urn:mace:dir:attribute-def:givenName"
        NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
    <saml:AttributeValue xmlns:xs="http://www.w3
.org/2001/XMLSchema" xsi:type="xs:string">Jeroen
    </saml:AttributeValue>
</saml:Attribute>
<saml:Attribute Name="urn:mace:dir:attribute-def:mail" NameFormat="urn
:oasis:names:tc:SAML:2.0:attrname-format:uri">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string"><--email-->
    </sa
            ml:AttributeValue>
</saml:Attribute>
<saml:Attribute Name="urn:mace:dir:attribute-def:sn" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
    <saml:At
            tributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">Oorschot, van
    </saml:AttributeValue>
</saml:Attribute>
<saml:Attribute Name="urn:m
ace:dir:attribute-def:uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:
                         type="xs:string"><--username-->
    </saml:AttributeValue>
</saml:Attribute>
<saml:Attribute Name="Initials" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
    <
            saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">J.J.
    </saml:AttributeValue>
</saml:Attribute>
<saml:Attribute Name="NameID"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string"><--username-->
    </
            saml:AttributeValue>
</saml:Attribute>
</saml:AttributeStatement>
`

**Comment by ambsw-technology** [comment]
I'm not sure where it's coming from as we had to move to [our own fork](https://github.com/ambsw/django-saml2-auth/tree/plugin-system) (note `plugin-system` branch) to get some features we needed, but my Django config includes for ADFS:

        SAML2_AUTH['NAME_ID_FORMAT'] = 'None'

Might work in the base package too.

**Comment by JeroenvO** [comment]
We are using ADFS with SAML1.1 which is apparently no longer supported ( @peppelinux helped me on this). Hopefully we can change to SAML2.0 and hopefully this will resolve this problem.

**Comment by JeroenvO** [comment]
Our server admin added a claim on the IDP "urn:oasis:names:tc:SAML:2.0:nameid-format:transient" and now it works 
Thanks for the support!

**Comment by JeroenvO** [comment]
Small sidenote, djangosaml/pysaml doesn't crash anymore, now the IdP crashes...

**Comment by peppelinux** [comment]
> Small sidenote, djangosaml/pysaml doesn't crash anymore, now the IdP crashes...

It's time to change the idp ...

**Comment by peppelinux** [comment]
Happy to see that everything went fine and to close this issue with a pleasant result
