### ISSUE TITLE
Temporary files not removed

### ISSUE THREAD

**Issue by tpazderka** [IdentityPython/pysaml2#629]
## Code Version
4.7.0
## Expected Behavior
Clean up the no longer necessary files.
## Current Behavior
Calling `entitites_descriptor` leaves files on disc (2 per call).
## Possible Solution
`make_temp` function creates the temporary files marked as for deletion and passes file descriptor to the caller. It should be possible to just close the file when no longer needed.
## Steps to Reproduce
1. Call `entities_descriptor` to create a valid XML
2. Inspect temporary file storage

**Comment by peppelinux** [comment]
Pysaml2 uses xmlsec1 as system call and It needs a xml file. As other issues related to xmlsec1 already exposed, we're facing the Need to implement a xmlsec wrapper in pure python. This Will let us to decide if use systemcall or xmlsec lib/api for xml validation.

I'm using pysaml2 v4.6.0 and this problem not exists with this version. Pysaml2 v4.7.0 and v4.8.0 have this problem.

**Comment by peppelinux** [comment]
See https://github.com/IdentityPython/pysaml2/issues/421

**Comment by peppelinux** [comment]
Fixed in this PR
https://github.com/IdentityPython/pysaml2/pull/634
