### ISSUE TITLE
create_logout_request() correct usage

### ISSUE THREAD

**Issue by PaulKovalov** [IdentityPython/pysaml2#635]
I use pysaml2 version 4.8.0 to implement SSO and SLO service, currently im stuck with creating logout request, The way i'm doing it is as follows:

```if not request.user.is_anonymous:
            saml2_client = _get_saml_client() # this works good for SSO, here it has changed endpoint of entityid
            rid, logout_request = saml2_client.create_logout_request(
            destination=identity_provider_endpoint,
            name_id=request.user.email, # we use email for nameID
            issuer_entity_id="https://localhost:8000/saml2_logout/",
            )
            print(logout_request.verify()) # this causes AttributeError, 'str' object has no attribute 'verify'
            return HttpResponseRedirect(logout_request) # this causes quote_from_bytes() expected bytes
```
for some reason create_logout_request returns str object, however when I try to print it
` print(logout_request)`
I'm getting `'str' object has no attribute 'become_child_element_of'` 
I couldn't find any documentation on how to create logout request, any help will be much appreciated

**Comment by peppelinux** [comment]
See djangosaml2.views, you'll find in It a common example

See also pysaml2/example

**Comment by PaulKovalov** [comment]
Well, I've checked the examples, they use 'global_logout' method, which uses 'do_logout' which uses 'create_logout_request'. If I use 'do_logout' I'm getting error in this part of 'do_logout' code:
`srvs = self.metadata.single_logout_service(entity_id,binding,"idpsso")` - it returns None and I'm seeing 
Unknown system entity: <idp_logout_endpoint>
No SLO 'urn:oasis:names:tc:SAML:2.0:bindings:SOAP' service
Unknown system entity: <idp_logout_endpoint>
No SLO 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST' service
Unknown system entity: <idp_logout_endpoint>
No SLO 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect' service

Anyway I would like to use create_logout_request method, and  I'm wondering why LogoutRequest instance returned by create_logout_request is str object
