### ISSUE TITLE
errors in ACS endpoint in sp-wsgi example

### ISSUE THREAD

**Issue by geo-s** [IdentityPython/pysaml2#636]
I'm trying to run modified sp-wsgi from examples. It sends AuthnRequest to external IDP SSO service with no problems, but when it returns to /acs/post endpoint (SAMLart is passed via POST) all I get is an empty response (in web browser) and value error (in server console) - see below.
In fact whatever is sent to this endpoint via POST generates this behavior.
If the ACS is requested via GET method the example returns HTTP code 404 and sends "Error parsing request or no request" to browser without any errors in the console.

## Code Version

Debian GNU/Linux 9 (stretch)
Python 2.7.13
pysaml2 - 4.8.0 (master)
CherryPy - 17.4.2 (examples require cherrypy>14.0.2)
## Expected Behavior

I guess that the SP page should be sent to browser with data from IDP.
## Current Behavior

```
ValueError("invalid literal for int() with base 10: ''",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1278, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1082, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/wsgi.py", line 151, in respond
    self.req.ensure_headers_sent()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1129, in ensure_headers_sent
    self.send_headers()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1146, in send_headers
    status = int(self.status[:3])
ValueError: invalid literal for int() with base 10: ''
```

## Steps to Reproduce

1. request ACS from sp-wsgi example via POST (could be any variable name and value)

**Comment by c00kiemon5ter** [comment]
Well, the problem I see here is 

```
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1146, in send_headers
    status = int(self.status[:3])
ValueError: invalid literal for int() with base 10: ''
```

which comes from an error on the cherrypy processing.
The error says that `self.status[:3]` is `""` (empty), and thus when `int()` tries to parse it to form the HTTP status code, parsing fails as no number is found.

What IdP is that? Is the response it sends back correct? I am not sure how to reproduce this - the example-idp (idp2) works fine with the example-sp (sp-wsgi).

**Comment by geo-s** [comment]
The IdP is a third-party server which is not public. The response seems fine (it's just SAML artifact), but no matter what is sent (or by who) towards acs endpoint - if it's via POST it generates this error, GET gives no error, only displays this info about empty request.
I wonder why the POST/GET makes such a difference.

**Comment by peppelinux** [comment]
The encoding errors would change from py27 to py3 and maybe this latter with the last pysaml2 release fixes it as is. Hope to get a feedback from you regarding a test in that direction, in the absence of it I believe that this thread will be closed in weeks. Thank you
