### ISSUE TITLE
Response class throws exception when message is empty & template is  just plain string (i.e without formatting characters )

### ISSUE THREAD

**Issue by anekix** [IdentityPython/pysaml2#644]
Passing a simple string (valid html) as templete to `Response` throws exception.
## Pysaml2 Version
4.8.0

## Current Behavior

consider this example:
```python
from saml2.httputil import Response

template = """<html><body>My Form</body></html>"""
Response(template=template)
```
`Response` class uses   `_response` method ,source for which  is:
```python
    def _response(self, message="", **argv):
        if self.template:
            message = self.template % message # this line?
        elif self.mako_lookup and self.mako_template:
          
       ........
```
The line defined as:
```python
message = self.template % message
```
will throw this exception 
```python
TypeError: not all arguments converted during string formatting
```
### Expected Behaviour
if `message=""` then it `_response` method should just return the  html template passed so that it could be sent as response.

###  Possible Fix:

```python

    def _response(self, message="", **argv):
        if self.template: 
            if message:
                message = self.template % message
            else:
                message = self.template
        elif self.mako_lookup and self.mako_template:
            argv["message"] = message
            mte = self.mako_lookup.get_template(self.mako_template)
            message = mte.render(**argv)
```

I might have missed if there is other way to send HTML response without any interpolation or my understanding of this method might be  wrong.

**Comment by ioparaskev** [comment]
I'm not sure this is a bug. It seems like a bad/confusing variable naming ~of this minimal "template engine function"~ that leads in such confusion.
In your case the template should be `<html>%s</html>` and the message should be `<body>My Form</body>`. The use of the `message` argument really depends on what you want to build. If you want to have a generic template that would format values during evaluation, then yes you should have something like:
```python
template="""<html><body>My Form has message1 %s and message2 %s </body></html>"""
Response(message=("testmsg1", "testmsg2"), template=template)
```
but if you want a simple html page (like your scenario), you have to split the template in two parts having the body as the `message` (as I said in the beginning).

Sidenote: Maybe `.format` could solve such issues (_although this would break backwards compatibility unless we end up with some "template engine" versioning option for the `Response` class_). In such cases we would have to use the `*` expansion in `.format` ending up with something like:
```python
if self.template:
    message = self.template.format(*message)
```
In your scenario it would work fine:
```python
In [1]: template = """<html><body>My Form</body></html>"""
In [2]: message = ""
In [3]: template.format(*message)
Out[4]: '<html><body>My Form</body></html>'
```
(which would of course work only for positional expansion formatting and would not work with named variables and dictionaries (where we would need `**` expansion))

**Comment by anekix** [comment]
yes , it seems more of a confusing variable naming.
