### ISSUE TITLE
DecryptError on parse_assertion

### ISSUE THREAD

**Issue by sgabb** [IdentityPython/pysaml2#649]
Hi,
we are trying to implement the library in a python django project but the library fails while trying to decrypt the assertion returned in the response from the Identity Provider.

## Code Version
4.8.0

## Expected Behavior
Decypt the saml response from the Identity Provider and get back a AuthnResponse wher identity is not null.

## Current Behavior
After executing **parse_authn_request_response(resp, entity.BINDING_HTTP_POST)** of the Saml2Client(Base) class, and then calling **get_identity()** (AuthnResponse class) we get an empty dict. 

While debugging the application to understand the problem, we found out that there is an error here:
https://github.com/IdentityPython/pysaml2/blob/25e9dc3b7466572a333a32c03cfc91ef3b9e696f/src/saml2/response.py#L951
The DecryptError is the following:
**DecryptError('No key was able to decrypt the ciphertext. Keys tried: []',)**

Here is a partial log of what happens:

- INFO 337 POST data dict_keys(['SAMLResponse'])
- INFO 663 next url /admin
- INFO 679 status: <ns0:Status xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></ns0:Status>
- INFO 681 ***Encrypted assertion***
- INFO 682 DecryptError: DecryptError('No key was able to decrypt the ciphertext. Keys tried: []',)
- INFO 683 *** DECRYPTING ASSERTIONS ***
- INFO 683 encrypted_assertion: <saml2.saml.EncryptedAssertion object at 0x7fd98dc5d6a0>
- INFO 684 ***Getting identity***
- INFO 684 AuthnResponse assertions: []
- INFO 685 --- AVA: {}
- INFO 685 Authn_response: <saml2.response.AuthnResponse object at 0x7fd98e5f8278>
- INFO 686 ***Getting identity***
- INFO 687 user_identity = get_identity(): <class 'dict'> - {}

Any idea of what could the issue?
Thanks in advance.

Gabrio

**Comment by peppelinux** [comment]
Hi Gabrio,
Here's my Django Notes on pysaml2
https://github.com/peppelinux/Django-Identity

Put encryption keypairs into metadata, It should use that.
If you're looking for a SP implementation take a look to djangosaml2 (and also to my fork 😉)
