### ISSUE TITLE
handle_logout_request bindings

### ISSUE THREAD

**Issue by rectalogic** [IdentityPython/pysaml2#651]
## Code Version
master

## Current Behavior

The following code in handle_logout_request:
https://github.com/IdentityPython/pysaml2/blob/788a695/src/saml2/client.py#L526

```python
        if binding == BINDING_SOAP:
            response_bindings = [BINDING_SOAP]
        elif binding == BINDING_HTTP_POST or BINDING_HTTP_REDIRECT:
            response_bindings = [BINDING_HTTP_POST, BINDING_HTTP_REDIRECT]
```
Won't `elif binding == BINDING_HTTP_POST or BINDING_HTTP_REDIRECT:` always be True because `BINDING_HTTP_REDIRECT` is a contant string so it will always be True in the `or`.

## Possible Solution

Not sure what this code is trying to do. I would like a way to force a preferred binding for IdP initiated SLO to my SP, currently it picks POST when both redirect and POST are supported by the IdP

**Comment by c00kiemon5ter** [comment]
yes, you are right, this will always evaluate to `True`. This should check if the `binding` is one of. 

---

You should leave the binding as `None` and [set `preferred_binding`](https://pysaml2.readthedocs.io/en/latest/howto/config.html#preferred-binding) on your config.
