### ISSUE TITLE
pylint-3.8 -E issues lots of errors

### ISSUE THREAD

**Issue by stroeder** [IdentityPython/pysaml2#675]
When scanning for errors (not style!) with pylint lots of messages are printed. There might be some false positives in there caused by mix-in classes but still there are many symbols found which are not available in PY3 anymore.

Check yourself e.g. with:
pylint-3.8 -E src/

Before I eventually try to fix things I'd like to know what's your opinion on pylint's output.

**Comment by ioparaskev** [comment]
pylint tends to be too verbose in some cases (especially the default config) so that's why most of us use flake8 usually.
Can you paste the output parts that you consider most serious for fixing?

**Comment by stroeder** [comment]
I did not write about style output of pylint's default configuration. This ticket is about running pylint with command-line option -E alias --errors-only: "In error mode, checkers without error messages are disabled [..]"

Thus pylint -E only reports missing imports, missing symbols, or similar. There can be false positives in case of mix-in classes (check "no-member").

But messages like these indicate that PY3 migration was not completed because PY2-only stuff is used:

************* Module saml2test.opfunc
src/saml2test/opfunc.py:5:0: E0401: Unable to import 'urlparse' (import-error)
************* Module saml2.ident
src/saml2/ident.py:143:27: E0602: Undefined variable 'unicode' (undefined-variable)

This code part is probably a left-over of a PY2.5 compat shim which is not correctly interpreted by pylint's introspection but could be simply removed nowadays:

************* Module saml2.s_utils
src/saml2/s_utils.py:385:42: E0602: Undefined variable 'sha' (undefined-variable)

**Comment by c00kiemon5ter** [comment]
Hello and thanks for filling in this issue. I will go through the list and fix those errors.

Not all of them are actual errors. Some have to do with the way the library was written, some with optional dependencies, some with python2 code. There was never a migration; pysaml2 supported both python versions until some point in time when we decided we should not give attention to python2 compatibility. As the library evolves python2 compatibility checks will be removed and hopefully the code will be a bit cleaner.

I will follow up with the fixes and a small report on pylint output.

**Comment by c00kiemon5ter** [comment]
The https://github.com/IdentityPython/pysaml2/tree/pylint-fixes branch is tracking the fixes.

**Comment by c00kiemon5ter** [comment]
See #686
