### ISSUE TITLE
Question: Reading Identity Provider Issuer from SAML response

### ISSUE THREAD

**Issue by vahedq** [IdentityPython/pysaml2#695]
I am not sure if this is the right place to post a question, but hoping you can help.

I have a multi-tenant system with multiple Identity providers and one ACS Endpoint (SP sign-in URL).

To create a SAML client and finish the auth flow, I'd need to look up the corresponding  metadata for the saml response in our DB. To do this, it seems like I need to first read the `issuer` from the saml response.

Is there an easy way to read issuer from saml response with pysaml2?

E.g.,
```
<saml2:Issuer 
     xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
     Format="urn:oasis:names:tc:SAML:2.0:nameid format:entity">
   http://www.okta.com/xyzxyzxyzxyzxyzxyz
</saml2:Issuer>
```

**Comment by c00kiemon5ter** [comment]
Have you initialized any object (ie, `saml2.client.Saml2Client`)? 
If you have initialized an object like `saml2.client.Saml2Client` then assuming this object is there and named `sp`

```python
import saml2

response = sp.parse_authn_request_response(response_xml, saml2.BINDING_HTTP_POST)
print(response.authn_response.issuer())
```

---

If not, then I guess the easiest way to parse the response and get the issuer would be:

```python
import saml2
import saml2.samlp

response = saml2.create_class_from_xml_string(saml2.samlp.Response, response_xml)
print(response.issuer.text)
```

**Comment by vahedq** [comment]
Thanks a bunch for your quick response @c00kiemon5ter. The second method worked. I will use the issuer to look up certificate from our backend to create `saml_client` and run the first method to check signature. Thanks again.

**Comment by c00kiemon5ter** [comment]
cheers, I'm closing this then for now ;)
