### ISSUE TITLE
XML parse error: 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte

### ISSUE THREAD

**Issue by vahedq** [IdentityPython/pysaml2#696]
I am submitting a SAML2 integration to Okta and using their test tool (http://saml.oktadev.com/), it seems like I was not handling compressed SAML Responses.

`saml_response` is a deflated SAML response.

If I call, 
```
client.parse_authn_request_response(saml_response, entity.BINDING_HTTP_POST)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 0: invalid continuation byte`
```

If I inflate and decode first:
```
decoded = decode_base64_and_inflate(decoded) 
client.parse_authn_request_response(decoded, entity.BINDING_HTTP_POST)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte
```

If I just decode and pass, this is what I get:
```
decoded = base64.b64decode(decoded) 
client.parse_authn_request_response(decoded, entity.BINDING_HTTP_POST)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 4: invalid start byte
```

## Code Version

`pysaml2==5.3.0`

## Expected Behavior

How can I add support for  deflated SAML responses? I am new to `pysaml2`

## Steps to Reproduce

1.
2.
3.
4.

**Comment by vahedq** [comment]
FWIW, this workround works for me:
```
saml_response = base64.b64encode(decode_base64_and_inflate(saml_response))
client.parse_authn_request_response(saml_response, entity.BINDING_HTTP_POST)
```

**Comment by peppelinux** [comment]
inflated/deflated wouldn't have to be used only in HTTP-REDIRECT or do I have miss something?
please let me know, thank you

**Comment by earonesty** [comment]
inflated/deflated is used for post and redirect depending on the provider.  need to do it, catch and try without, will post pr
