### ISSUE TITLE
Multiple ways to get logout_requests_signed, are we using the correct one now?

### ISSUE THREAD

**Issue by dhensen** [IdentityPython/pysaml2#701]
In b8539198 there was a change where `self.logout_requests_signed` was changed to `self.config.logout_requests_signed`.
I'm wondering what the reason was other than the linter message in the commit message stating that "E1101: Instance of 'Saml2Client' has no 'logout_requests_signed' member (no-member)". If you see the saml2.client_base.Base constructor, you can see that a list of attribute_defaults are set as member vars. Probably a case of the linter not being smart enough.

So my claim is this: the old way worked just find (`self.logout_requests_signed`)

Let's see why:
The `self.config.logout_requests_signed` uses the instance variable, this is obvious. But saml2.config.Config:load_special uses the `SPEC` dictionary to load your custom config given a context ('sp' in case of logout_requests_signed) resulting in a "protected" member var names `_sp_logout_requests_signed`. This differs from self.config.logout_requests_signed, which value is initialized to None.

So from my viewpoint this solves a linter issue, but introduced a bug that we are running into now.

## Code Version

5.3.0

## Expected Behavior
Given a custom config I expect the value of self.config.logout_requests_signed to be False, when I set logout_requests_signed to False in my custom config.

## Current Behavior
Given a custom config where logout_requests_signed is set to False, the value of self.config.logout_requests_signed is None. My custom config is not propagated. (The code uses setattr with `sp` as context and sets it on var `_sp_logout_requests_signed` )

## Possible Solution
- Revert change.
- Let there be only one way to access logout_requests_signed. Remove the member vars from Saml2Client and force us to use the Config object. OR Let it this way and proxy the dynamically set member vars to relevant entries in the Config object.

**Comment by c00kiemon5ter** [comment]
Hello, you're right, this change is wrong. I'm reverting and a preparing a release for this. 
See https://github.com/IdentityPython/pysaml2/releases/tag/v6.1.0

**Comment by dhensen** [comment]
Thank you for your quick response! much appreciated!
