### ISSUE TITLE
Azure AD Saml implementation

### ISSUE THREAD

**Issue by shakthifuture** [IdentityPython/pysaml2#719]
Is it possible to implement azure AD sign on using this library? Any samples?

**Comment by peppelinux** [comment]
Probably you're looking for a SP implementation for a ADFS SSO Service.
I know that pysaml2 can work with it, even as IdP (with Microsoft SP) but I've not tested them.

Guys with djangosaml2 and uniauth, some pysaml2 wrappers,,get them to work but without any changment on pysaml2, it would work as it is.

**Comment by peppelinux** [comment]
Please try a default configuration with adfs attr maps that's already in pysaml2 example folder. Fill free to open another issue if you'll have troubles

**Comment by peppelinux** [comment]
That's for you
https://github.com/IdentityPython/pysaml2/pull/597#issuecomment-653248977

**Comment by mhoangpayfone** [comment]
@shakthifuture were you able to implement azure AD SSO? I'm in the process of integrating AZURE SSO with my service but not getting anywhere. Do you guys know if there are any examples? Thank you in advance.

**Comment by peppelinux** [comment]
Afaik  uniAuth (a pysaml2 based idp) works with adfs. Gus Duarte, a uniAuth stargaizer, did It.

Djangosaml2 v1.0.0, a pysaml2 based SP, works with azure/adfs. See thread in it's closed issues
