### ISSUE TITLE
Use this package for SAML signature verification and resigning SAML

### ISSUE THREAD

**Issue by santoshdahal12** [IdentityPython/pysaml2#730]
## Code Version
master

## Expected Behavior
Can we use this package just to verify the SAML  signature and resign it again ? 
Example how to use this package just to verify signature of SAML token. Does this check XML signature wrapping attacks while doing the signature verification. Is there any documentation of APIs that points to these? 

## Current Behavior
Documentation only gives example about implementing this library as SP and IDP. 

## Possible Solution
Documentation that shows how we can use this package just for SAML verification and resigning 

## Steps to Reproduce

1.Google this package to see if we can just use for signature verification and resigning, we will end up getting confused.

**Comment by peppelinux** [comment]
xmlsec1 can do that for you, that's pysaml's sign/enc backend. If you go through pysaml2 for do that use this class

https://github.com/IdentityPython/pysaml2/blob/db417d8be5195a9416a4245d9b7289580e1a2fe5/src/saml2/sigver.py#L672

**Comment by c00kiemon5ter** [comment]
See also this issue with an example
https://github.com/IdentityPython/pysaml2/issues/735#issuecomment-707199035

**Comment by peppelinux** [comment]
> xmlsec1 can do that for you, that's pysaml's sign/enc backend. If you go through pysaml2 for do that use this class
> 
> https://github.com/IdentityPython/pysaml2/blob/db417d8be5195a9416a4245d9b7289580e1a2fe5/src/saml2/sigver.py#L672

Ops, that was for encryption!
Yes, we should documento the API, there would be a lot of utilities that could be easily build from that
