### ISSUE TITLE
Configuration options to sign the logout response

### ISSUE THREAD

**Issue by maxbes** [IdentityPython/pysaml2#733]
## Code Version
6.1.0

## Expected Behavior
I use pysaml2 through djangosaml2 as a SP. My IdP requires logout responses to be signed in the context of IdP-initiated logout.

## Current Behavior
Currently, djangosaml2 calls pysaml2 like this:

```
            http_info = client.handle_logout_request(
                data['SAMLRequest'],
                subject_id,
                binding,
                relay_state=data.get('RelayState', ''))
```
In the absence of a `sign` parameter, pysaml assumes a default value of False, and logout responses are not signed. In the current state of the code, it is up to the calling application (djangosaml2 in my case) to decide whether or not SAML logout responses should be signed.

However, pysaml already has a logout_requests_signed option that will cause logout requests (initiated by the SP) to be signed if the calling application is not explicit about signing. 

## Possible Solution
I am not sure about the best way to solve this, my options so far:

* Add an option to Djangosaml2 to decide whether or not LogoutResponses should be signed (and moving this issue to the djangosaml2 project)
* Assume that IDPs who want logout requests to be signed also want responses to be signed, and change `handle_logout_requests` so that it, if `sign` is not passed by the application, it will decide whether or not to sign the request depending on the value of `settings.logout_requests_signed`. This is what `do_logout` currently does. This solution means that the `logout_requests_signed` setting will do a little more than what it says on the tin.
* Add a new `logout_responses_signed` option to pysaml2

Let me know which solution you prefer, and I will submit a PR for it

**Comment by peppelinux** [comment]
Hi @maxbes, I think that this should be related to djangosaml2.

We can handle It in this way:
Check idp metadata, if It need signed logout requests then we'll add the sign=True parameter in the request

**Comment by peppelinux** [comment]
Regarding pysaml2 I agree about adding "want_logout_request_signed" in idp parameters

https://github.com/IdentityPython/pysaml2/blob/ec2ccd72beb12ab1f81c63c46953aaa764142209/src/saml2/config.py#L112

@maxbes would you like to try a PR here?
