### ISSUE TITLE
AuthnResponse.verify doesn't raise an exception for a response that is no longer valid

### ISSUE THREAD

**Issue by tpazderka** [IdentityPython/pysaml2#735]
## Code Version
6.2.0
## Expected Behavior
Raise an exception
## Current Behavior
Returns `AuthnResponse`.
## Possible Solution
[This](https://github.com/IdentityPython/pysaml2/blob/v6.2.0/src/saml2/response.py#L1033) code still expects the old behavior with raisin an error instead of checking for the return value.
## Steps to Reproduce
1. Take an old response and try to run `verify()` method.

**Comment by peppelinux** [comment]
Hi @tpazderka, can you post the code example for the expected behaviour and the current one?

I don't have that code in mind, if you can share additional references this could help us joining in debate about how to handle this issue

**Comment by tpazderka** [comment]
```
from saml2.client import Saml2Client
from saml2.config import SPConfig

_, message = Saml2Client(config=SPConfig()).create_authn_request('https://example.cz/saml/sso/redirect/')

message.issue_instant = '2010-10-10T12:00:00Z'   # Clearly too old

message.verify()
```

The above code returns `True` although it should in fact return `False` as the message is clearly too old to be valid.

**Comment by c00kiemon5ter** [comment]
hello,

what you have there is a `message` var that is a `saml2.samlp.AuthnRequest` object; what you are verifying is the (xml) structure, not the SAML2 requirements. To do the later a lot more things are involved. Taking your code as an example (and with minimal parameters), you would need to load the message into a `saml2.request.AuthnRequest` object and call `.verify()` on that.

```python
import saml2
from saml2.client import Saml2Client
from saml2.config import SPConfig
from saml2.request import AuthnRequest
from saml2.sigver import SecurityContext
from saml2.sigver import CryptoBackendXmlSec1
from saml2.attribute_converter import ac_factory

sec_backend = CryptoBackendXmlSec1(xmlsec_binary="/usr/local/bin/xmlsec1")
sec_context = SecurityContext(sec_backend)
authn_req = AuthnRequest(sec_context, "https://example.cz/saml/sso/redirect/", ac_factory())

_, message = Saml2Client(config=SPConfig()).create_authn_request('https://example.cz/saml/sso/redirect/')
assert authn_req.loads(message.to_string(), binding=saml2.BINDING_HTTP_REDIRECT).verify() is True

message. issue_instant = '2010-10-10T12:00:00Z'
assert authn_req.loads(message.to_string(), binding=saml2.BINDING_HTTP_REDIRECT).verify() is False
```

**Comment by tpazderka** [comment]
OK, sorry for the confusion. I was trying to create a minimal example and I have minimized too much.

The error is probably somewhere in the Client code as `parse_authn_request_response` now doesn't fail for the outdated response.

**Comment by c00kiemon5ter** [comment]
I'm closing this for now, but feel free to add more to and reopen it as needed.
