### ISSUE TITLE
Unused service.sp.idp configuration option

### ISSUE THREAD

**Issue by clokep** [IdentityPython/pysaml2#739]
The [configuration discusses an `idp` setting](https://pysaml2.readthedocs.io/en/latest/howto/config.html#idp) under the `sp` section with the description:

> Defines the set of IdPs that this SP is allowed to use; if unset, all listed IdPs may be used. If set, then the value is expected to be a list with entity identifiers for the allowed IdPs.

As far as I've been able to see this option is unused inside of pysaml2.

## Code Version
db417d8be5195a9416a4245d9b7289580e1a2fe5

## Expected Behavior
This option is removed from the configuration documentation or is used.

## Current Behavior
The option is unused.

## Possible Solution
🤷

**Comment by peppelinux** [comment]
mmh... AFAIK that option works in djangosaml2 and it strictly belong to pysaml2, it works

**Comment by clokep** [comment]
Looking at the [djangosaml2 docs](https://github.com/knaperek/djangosaml2#pysaml2-specific-files-and-configuration) they seem to have this setting as a dict, not a list as the docs state. I'll take a closer look though.

**Comment by peppelinux** [comment]
Hey @clokep I hope that you went further with this ... Is it time to close this question?
Would you like to put a PR on pysaml2's documentation regarding this weakness?

**Comment by clokep** [comment]
> Hey @clokep I hope that you went further with this ... Is it time to close this question?

I didn't have a chance to look further into djangosaml2. I don't know enough about the relationship between these two projects to understand why pysaml2 (a dependency of djangosaml2) would include an option only used by that project.

I could provide a PR which removes this documentation, but I'm now unsure if that's accurate or not.

**Comment by peppelinux** [comment]
take your time, I'll back on this on gen 2021 ;)
