### ISSUE TITLE
Security issue in pysaml2

### ISSUE THREAD

**Issue by bawolff** [IdentityPython/pysaml2#755]
I believe i found a fairly significant issue in pysaml2 with the way signatures are verified.

I tried to follow https://github.com/IdentityPython/Governance/blob/master/idpy-incidentresponse.md and emailed incident-response@idpy.org about a week ago . However nobody has acknowleged recieving my email.

Can you confirm that that email is how you wish to recieve security reports, and that you recieved mine? If that's not how you wish to recieve security reports, please let me know how you would like me to send the report.

Thanks,
Brian

**Comment by c00kiemon5ter** [comment]
Hello, and thanks for the nudge. I think the message was withheld. I will at it asap and catch up through that channel.

**Comment by spaceone** [comment]
CC

**Comment by bawolff** [comment]
@c00kiemon5ter  Apologies for the following vain request, but any chance my github account could be linked into the credits for https://github.com/IdentityPython/pysaml2/security/advisories/GHSA-5p3x-r448-pc62 so it shows up in the list of security advisories of contributed to at https://github.com/advisories?query=credit%3Abawolff ?

Thanks,
Brian

**Comment by c00kiemon5ter** [comment]
Hello @bawolff 

I've added your account as part of the credits. I guess this will show up on the query once it is re-processed and the relevant cache from GitHub cleared.
