### ISSUE TITLE
Remove version 6.4.0 fro PyPi

### ISSUE THREAD

**Issue by tpazderka** [IdentityPython/pysaml2#756]
Version `6.4.0` incorrectly allows to be installed under Python 3.5 but has syntax errors under is. The release `6.4.1` fixed that, but `6.4.0` is still the newest available release for python 3.5 which causes a broken install. This release should be removed from PyPi to allow correct installation of the latest available version (`6.3.1`) under python 3.5.

**Comment by c00kiemon5ter** [comment]
The same syntax error is there in codepaths that you probably do not use. I don't think we should go back and remove all versions that do not satisfy a certain python version (which has reached end of support). Having set `python_requires` earlier would have been nice to ensure that during installation you are notified about this incompatibility. Until we had that, you only knew when you run the code - dynamic languages are like that. Additionally, pysaml2 always indicated support for py36 or newer through its metadata classifiers, from the point in time where it dropped python2 support. 
Thanks for the consideration.

**Comment by tpazderka** [comment]
Well, we are using `6.3.1` for both client and server under python 3.5 without any issues, so the `6.4.0` is the first one that fails to install and run.
