### ISSUE TITLE
"LDAPSocketOpenError" even when removing 'ldap_peoples' and 'multildap' from INSTALLED_APPS in 'settingslocal.py'

### ISSUE THREAD

**Issue by omizrahi99** [IdentityPython/pysaml2#760]

**Comment by omizrahi99** [comment]
I realized this is probably an error with uniAuth (django implementation of pysaml2) instead, so I will post there. Feel free to delete this issue. My apologies.

**Comment by peppelinux** [comment]
Thank you @omizrahi99 
This issue Is uniAuth related
