### ISSUE TITLE
IssueInstant attribute prior to IssueInstant of the Request

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/pysaml2#767]
A PySAML2 SP seems to work properly even if it receive a Response like the following:
````
<samlp:Response Destination="http://sp1.testunical.it:8000/saml2/acs/" ID="_c19ec300-6e47-4ea7-86f0-a82bc6747440" InResponseTo="id-eamgZfiD3S1TDNg1a" IssueInstant="2021-01-24T01:05:01Z" Version="2.0" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">

[...]

<saml:Assertion ID="_b431a7c8-4ad3-479a-b867-a5d9625e98bb" IssueInstant="2018-09-06 16:00" Version="2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
````

Same behaviour with a IssueIstant prior to the AuthnRequest 

````
<samlp:Response Destination="http://sp1.testunical.it:8000/saml2/acs/" ID="_cd3bb191-9934-485b-98ec-87676cc1e023" InResponseTo="id-VOHjtNzUB1vnQ2i90" IssueInstant="2018-01-01T00:00:00Z" Version="2.0" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
````

**Comment by c00kiemon5ter** [comment]
The `IssueInstant` attribute is a timestamp. It appears on the `samlp:AuthnRequest`, the `samlp:Response` and the `saml:Assertion`.

I don't think that the specification defines any relationship between the timestamps. I can see the following

> The Service Provider site MUST check the validity period of all assertions obtained from the
> Identity Provider site and reject expired assertions. A Service Provider site **MAY** choose to
> implement a stricter test of validity for SSO assertions, such as requiring the assertion’s
> IssueInstant or AuthnInstant attribute value to be within a few minutes of the time at
> which the assertion is received at the Service Provider site.

and

> The destination site MUST check the validity period of all assertions obtained from the source
> site and reject expired assertions. A destination site **MAY** choose to implement a stricter test of
> validity for SSO assertions, such as requiring the assertion’s IssueInstant or AuthnInstant
> attribute value to be within a few minutes of the time at which the assertion is received at the
> destination site.

---

What I worry mostly, is that we do check the `IssueInstant` on the `samlp:AuthnRequest` and the `samlp:Response`, but do we really check it on the `saml:Assertion`? I have to check.
