### ISSUE TITLE
Parameter "logout_requests_signed" in config not signing logout requests

### ISSUE THREAD

**Issue by joachimBurket** [IdentityPython/pysaml2#793]
## Code Version
6.5.1

## Expected Behavior
I'm using pysaml2 through djangosaml2 as an SP. The ADFS IdP requires logout requests to be signed.

With this configuration:
```python
SAML_CONFIG = {
    ...
    "service": {
        "sp": {
            "logout_requests_signed": True,
        }
    }
}
```

The logout requests (initiated by the SP) should be signed.

## Current Behavior

The request is not signed and the IdP doesn't accepts it.

## Possible Solution

The djangosaml2 library calls the `global_logout()` method to initiate the logout, and doesn't sets the `sign` argument. So either in `global_logout()` or `do_logout()` methods, the following could be added:

```python
if sign is None:
    sign = self.logout_requests_signed
```

**Comment by peppelinux** [comment]
I made it to work in djangosaml2 using HTTP-POST binding 
https://djangosaml2.readthedocs.io/contents/setup.html#preferred-logout-binding

**Comment by c00kiemon5ter** [comment]
Hello, this is not intended and should be working.

The HTTP-POST should also not be working; it is working because the same code path is affected by a different configuration option.

**Comment by c00kiemon5ter** [comment]
Please, if you can verify with the latest HEAD (4c550f5370862cb3ed3b02dad346ce2fff71aeb3) that'd be nice.

**Comment by joachimBurket** [comment]
Hello,

I tested with the latest HEAD on my project and it is working as intended. Thanks for the fix!

**Comment by berkowitzi** [comment]
Hi @c00kiemon5ter -- is there any chance that you could publish a release containing this patch?
Thanks!

**Comment by c00kiemon5ter** [comment]
Hello, I will create a release soon. Sorry this did not happen faster.
