### ISSUE TITLE
Setting up a RelayState in an app

### ISSUE THREAD

**Issue by TediMoci** [IdentityPython/pysaml2#795]
Hello everyone, I hope this is the right place to ask this question, as I figured you'd be able to help me the most after trying to find a solution for a while. I have used the pysaml2 library to create a simple Service Provider that uses Okta as an iDP. This is how it looks: https://pastebin.com/TKaBP9Rp

Now what I'm trying to do is this:
1) In the first request, add a RelayState with a random nonce
2) Then, when the app reviews the response from the iDP, it needs to check if the RelayState corresponds to what was given initially
3) If yes, it should proceed with the authentication, otherwise not

Is it possible to do that in the library, and what would be the easiest way to handle it?

**Comment by TediMoci** [comment]
Nevermind, looking at the code I realized it was done via the following:
saml_client.prepare_for_authenticate(
        relay_state="something",
    )

**Comment by rrauenza** [comment]
@TediMoci How did you retrieve the relay state on the ACS side?
