### ISSUE TITLE
How to set Authentication Context?

### ISSUE THREAD

**Issue by anjaseidel** [IdentityPython/pysaml2#798]
Hi, could you give me a hint how I can add the Authentification Context to the idp config file? I would like to use *PasswordProtectedTransport*. From https://github.com/IdentityPython/pysaml2/blob/c1fab71cf9f24dce4cc8985061c45a19481dcec0/src/saml2/authn_context/__init__.py#L14 I see that it has to be possible somehow, but unfortunately I just can't get it to work ... Many thanks in advance!

**Comment by c00kiemon5ter** [comment]
Hello, you cannot set the authentication context class ref through the config file.

At some point your IdP should be calling into `saml2.server:create_authn_response()` which accepts `authn` as an argument. 
`authn` is a a dict that looks like:

```python
{'authn_auth': 'https://localhost:8088',
 'class_ref': PASSWORDPROTECTEDTRANSPORT}
```

**Comment by anjaseidel** [comment]
Hi @c00kiemon5ter, many thanks!
