### ISSUE TITLE
Metadata refresh not supported (for local and remote metadata)

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [IdentityPython/pysaml2#808]
## Code Version

7.0.1

## Expected Behavior

Metadata periodically refreshed.

## Current Behavior

Metadata just one-off loaded.

## Possible Solution

Hi,

My understanding of metadata loading in pysaml2 is that metadata gets loaded when pysaml2 is initialised, validity (signature, validUntil) gets checked at the point in time - and that's it.

This is perfectly fine when pysaml2 gets used in a one-off task, but not so desirable in a long-running application - and I'm using it with SATOSA running with pysaml2 backend.

Keeping the in-memory copy of the fetched metadata indefinitely, without a refresh, means:
* any changes to the metadata would be ignored - so e.g. new IdPs would not be recognised by this SP
* the metadata could be used past its `validUntil` (it's only checked at load time), so compromised keys IdP that have been rolled over in the metadata would still be trusted by this SP.

I think this should be addressed - ideally specifying a refresh period for each metadata source.  After this period, a refresh should be attempted.  Also, the original `validUntil` should be kept alongside the in-memory copy of the metadata - and past the `validUntil`, the in-memory copy should be dropped.  (This behaviour could be made optional).

As for a way to address this, I'm happy to implement this and send a Pull Request in, but I wanted to get a feedback on the ideas first - hence this issue report.

I expect a background refresh thread (which is used e.g. in Java and C++ SAML implementations) would not be ideal for a Python library.

However, refreshing the metadata only when needed (when serving a client request) could introduce undesirable delays on requests that trigger the refresh.

My current idea for a solution is to add a metadata refresh function that applications using pysaml2 could call - and metadata refresh would happen within this function.

In case of SATOSA, the call of the function could be exposed via a specific URL - which could be fetched from a cron job.  This approach is for example used by SimpleSAMLphp.

How does this all sound ?

I look forward to hearing back on what solution would sound acceptable to this project - thanks a lot in advance for getting back to me.

Cheers,
Vlad

**Comment by peppelinux** [comment]
I'd suggest to use and mdq server for this, where pyff does the job and a http static serve Will complete the task.

Your idea Is very good but a mdq server Is Better ihmo

**Comment by vladimir-mencl-eresearch** [comment]
Pull Requests submitted:
#809 
IdentityPython/SATOSA#370

**Comment by c00kiemon5ter** [comment]
> My current idea for a solution is to add a metadata refresh function that applications using pysaml2 could call - and metadata refresh would happen within this function.
>
> In case of SATOSA, the call of the function could be exposed via a specific URL - which could be fetched from a cron job. This approach is for example used by SimpleSAMLphp.

In general, I agree with @peppelinux that an mdx service is the proper way to do this.

I like the idea of providing a function that is externally invoked "somehow".

Thanks for the idea and PR

**Comment by vladimir-mencl-eresearch** [comment]
Hi @c00kiemon5ter ,

I also agree that especially for large metadata aggregates, MDQ is the best option.

However, if loading a metadata XML file is supported, I think reload should be supported as well .... so I hope #809 can be acceptable for that.

Cheers,
Vlad
