### ISSUE TITLE
Incorrect stripping of armoring in certificate files included in metadata

### ISSUE THREAD

**Issue by tpazderka** [IdentityPython/pysaml2#831]
## Code Version
7.0.1

## Expected Behavior
Include only certificate content in metadata.

## Current Behavior
Includes certificate with armor text in metadata.

## Possible Solution
The helper function assumes that the armoring is on the first and last line of the file. This fails if there is a comment and/or empty line at the beginning/end of the file. It would be better to use `index` to lookup the position of the armor text and use the resulting indexes for slicing.

https://github.com/IdentityPython/pysaml2/blob/c1fab71cf9f24dce4cc8985061c45a19481dcec0/src/saml2/metadata.py#L849-L852

## Steps to Reproduce
1. Create a certificate with an empty line at the beginning/end of the file
2. Create metadata using the certificate
3. Examine metadata element `KeyDescriptor` and the content of the enclosed `X509Certificate`

**Comment by c00kiemon5ter** [comment]
closed by a9244357
