### ISSUE TITLE
How do i provide pysaml2 with additional xsd files to support extended schemas?

### ISSUE THREAD

**Issue by grindhold** [IdentityPython/pysaml2#833]
I need to validate against an extended schema for which my customer provided me with an xsd file. I cannot find anything about that in the docs. I tried to use the 'extension_schemas' config variable but it seems to want a python module, not an xsd-file. How can validating with  an additional schema file be accomplished? Is it even possible at the moment?

**Comment by c00kiemon5ter** [comment]
hello, right now there is no mechanism to allow you to do this, but it's an interesting idea to have something along those lines.

What you can do atm is to patch `saml2.xml.schema` to have the schema validator load your file; see,
https://github.com/IdentityPython/pysaml2/blob/5583f16/src/saml2/xml/schema/__init__.py

Give this a try, and let us know.
