### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by manser-xiq** [IdentityPython/pysaml2#837]
I am trying to implement Single Logout and when I call  the `create_logout_response()` then I am getting error on `issuer.text`. I am calling the logout response with the following parameters:

```py
saml_client.create_logout_response(request=logout_request, bindings=entity.BINDING_HTTP_POST)
```

## Code Version

Getting error on this line.

```py
    entity_id = request.issuer.text.strip()
```

## Expected Behavior

```
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by c00kiemon5ter** [comment]
hello, 

to create a LogoutResponse the code needs to know which binding/URL to use. To do that it needs to look into the metadata. To check the metadata it needs to know the entityID of the issuer of the LogoutRequest. The entityID is expected to be part of the request as the `<Issuer>` element.

Based on the core spec and XSD, the `<Issuer>` element is required for `<Assertion>`s, but it is optional for any `RequestAbstractType` or `StatusResponseType`.

It seems that the LogoutRequest you generate does not contain an `<Issuer>` element. The assumes it will be there and fails. To be able to reply to the request, the code needs to find where to send the reply to. That is based on the entityID of the issuer of the request. Without an `<Issuer>` element, I don't see a way that this can be done.

**Comment by c00kiemon5ter** [comment]
ok; the Logout profile dictates that.

> ### 4.4.4.1 <LogoutRequest> Usage
>
> The `<Issuer>` element MUST be present and MUST contain the unique identifier of the requesting entity; the `Format` attribute MUST be omitted or have a value of `urn:oasis:names:tc:SAML:2.0:nameid-format:entity`.
> The requester MUST authenticate itself to the responder and ensure message integrity, either by signing the message or using a binding-specific mechanism.
> The principal MUST be identified in the request using an identifier that strongly matches the identifier in the authentication assertion the requester issued or received regarding the session being terminated, per the matching rules defined in Section 3.3.4 of [SAMLCore].

**Comment by c00kiemon5ter** [comment]
So, your LogoutRequest must include an `<Issuer>` element, through which the code will lookup in the metadata the right binding to return the location where the LogoutResponse will be sent.

That should fix the issue you see and you would comply with the spec.

---

From the library side, we should probably raise a descriptive error if the `<Issuer>` is missing.
