### ISSUE TITLE
How to create a saml:AttributeStatement? Just want to pass UserID/Subject - no clear docs

### ISSUE THREAD

**Issue by bjm88** [IdentityPython/pysaml2#838]
Hello

I followed entire `~/examples/idp/idpy.py` and have a working SAML response (IDP initiated, no SP needed to start)
however SamlTools shows warning on the response validation:
```
THE SAML RESPONSE VALIDATION CAN FAIL ON ONELOGIN'S SAML TOOLKIT
The Assertion should include 1 AuthnStatement element
```

And if I use this library to stand up an SP service provider and pass the response to that it gets error
```
The Assertion must include an AuthnStatement element
```

It's not clear at all in example or docs how to add a `AuthnStatement` or `Attribute`.  I see the attribute map config and entity attributes, but they don't seem to do anything, or cannot connect the dots from how I'm setting up the SAML Response.

my config looks like this:

```json
"service":{
   "idp":{
      ...
      "policy":{
         "default":{
            "lifetime":{
               "minutes":60
            },
            "attribute_restrictions":"None", # means all I have
            "name_form":"NAME_FORMAT_URI",
            # "entity_categories":["swamid", "edugain"]
         }
      },
      ...
      "allow_unknown_attributes":true,
      ...
      "entity_attributes":[
         {
            "name_format":"urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
            "name":"urn:oasis:names:tc:SAML:profiles:subject-id:req",
            # "friendly_name is not set
            "values":["any"]
         }
      ]
      ...
```

Then in making SAML response:

```py
name_id = IDP.ident.get_nameid(identity["user_id"], name_id_policy, sp_name_qualifier, name_qualifier)
_resp = IDP.create_authn_response(identity, in_response_to, destination, sp_entity_id, userid=identity["user_id"], binding=BINDING_HTTP_POST, name_id=name_id)
http_args = IDP.apply_binding(binding_out, "%s" % _resp, destination, response=True)
```

can anyone help me?

**Comment by c00kiemon5ter** [comment]
hello @bjm88 

I think what you're missing is the authentication context, which will trigger the creation of the `AuthnStatement`.

```py
from saml2.authn_context import UNSPECIFIED

auth_info = {"class_ref": UNSPECIFIED}
_resp = IDP.create_authn_response(
    identity,
    in_response_to,
    destination,
    sp_entity_id,
    userid=identity["user_id"],
    binding=BINDING_HTTP_POST,
    name_id=name_id,
    authn=auth_info,
)
```

**Comment by c00kiemon5ter** [comment]
I will close this now, but do reopen if you think this is not solving your issue.

**Comment by bjm88** [comment]
hi @c00kiemon5ter thank you!!  Please share a way we can "donate" aka tip for the help.  The documentation on this lib is really lacking and this is very useful, we greatly appreciate it.

This did solve that issue, and our SAML response looking good now, except what I hope is last error...

There is no AttributeStatement on the Response

how would we control adding an attribute like so:
<ns1:Attribute FriendlyName="userId" Name="userId" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
  <ns1:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">Scott</ns1:AttributeValue>
</ns1:Attribute>

We have configured in ipd a policy (which I think applies to attributes ?)
"policy": {
                    "default": {
                        "lifetime": {"minutes": 60},
                        "attribute_restrictions": None, # means all I have
                        "name_form": NAME_FORMAT_URI,
                        #"entity_categories": ["swamid", "edugain"]
                    },
                },
and entity attributes and mapping config, but I'm not sure how we reference it or ensure aligned in creating response.  We just want to add the userID as an attribute...
"encrypt_assertion": False,
                "sign_response": True,
                "secret": "" , #used in relay state encryption
                #"subject_data": "./idp.subject",
                "name_id_format": [NAMEID_FORMAT_TRANSIENT,
                                NAMEID_FORMAT_PERSISTENT],
                "allow_unknown_attributes": True,
                "entity_attributes": [
                    {
                        "name_format": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
                        "name": "urn:oasis:names:tc:SAML:profiles:subject-id:req",
                        # "friendly_name" is not set
                        "values": ["any"],
                    },
                    ]
            },
        },
        "debug": 1,

        "attribute_map_dir": "./app/python_api/resolvers/saml-soo-attribute-maps",

and we have mapping file...though its confusing if we configure directoyr does it look for all files in that ??
MAP = {
    "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
    "fro": {
        'urn:mace:dir:attribute-def:aRecord': 'aRecord',
        'urn:mace:dir:attribute-def:aliasedEntryName': 'aliasedEntryName',
        'urn:mace:dir:attribute-def:aliasedObjectName': 'aliasedObjectName',
        'urn:mace:dir:attribute-def:associatedDomain': 'associatedDomain',
        'urn:mace:dir:attribute-def:associatedName': 'associatedName',
        'urn:mace:dir:attribute-def:userid': 'userid',
    },
    "to": {
        'aRecord': 'urn:mace:dir:attribute-def:aRecord',
        'aliasedEntryName': 'urn:mace:dir:attribute-def:aliasedEntryName',
        'aliasedObjectName': 'urn:mace:dir:attribute-def:aliasedObjectName',
        'associatedDomain': 'urn:mace:dir:attribute-def:associatedDomain',
        'associatedName': 'urn:mace:dir:attribute-def:associatedName',
        'userid':'urn:mace:dir:attribute-def:userid' ,

    }
}

**Comment by bjm88** [comment]
focusing this base to subject/user ID and not actually attributes, trying to control this subject value
<ns1:Subject>
      <ns1:NameID NameQualifier="https://mychart-np.atlantichealth.org/MyChartPOC" SPNameQualifier="https://mychart-np.atlantichealth.org/MyChartPOC" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">b4877a209b0c0070103296460ac5f8b38abfbbad67ed4c4e69f1907d3365ab91</ns1:NameID>
      <ns1:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <ns1:SubjectConfirmationData NotOnOrAfter="2022-01-06T20:40:54Z" Recipient="https://mychart-np.atlantichealth.org/MyChartPOC/Authentication/Saml/Login"/>
      </ns1:SubjectConfirmation>
    </ns1:Subject>

to not be a random ID and just what we pass as user_id.  Is that right or reasonable ?  What is this random value the librariy creates?  causing errors with our SP that it cant' find the user.  we share a user_id.
