### ISSUE TITLE
How to pass a userId in SAML attribute or other way ?

### ISSUE THREAD

**Issue by bjm88** [IdentityPython/pysaml2#839]
No clear way in example code or documentation exactly 

While creating a SAML response (in an IDP initiated unsolicited SSO), getting an error on SP service provider side:

> There is no AttributeStatement on the Response

Another ticket (#838) was closed before full resolution.
@c00kiemon5ter any help here would be greatly appreciated, thanks!

---

IDP response creation code is below:

```py
auth_info = {"class_ref": UNSPECIFIED}
name_id = IDP.ident.get_nameid(identity["mrn"], name_id_policy, sp_name_qualifier, name_qualifier)
_resp = IDP.create_authn_response(
  identity,
  in_response_to,
  destination,
  sp_entity_id,
  userid=identity["mrn"],
  binding=BINDING_HTTP_POST,
  name_id=name_id,
  authn=auth_info,
)
http_args = IDP.apply_binding(binding_out, "%s" % _resp, destination, response=True)
return generateSamlResponse(binding_out, http_args)
```

How can I pass the logged-in user as SAML attribute or other standard way in SAML? The identity `mrn` is the value.
How would we control adding an attribute like so:

```xml
<ns1:Attribute FriendlyName="userId" Name="userId" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
  <ns1:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">Scott</ns1:AttributeValue>
</ns1:Attribute>
```

We have configured in IdP a policy (which I think applies to attributes ?)

```json
"policy": {
  "default": {
    "lifetime": {"minutes": 60},
    "attribute_restrictions": None, # means all I have
    "name_form": NAME_FORMAT_URI,
    #"entity_categories": ["swamid", "edugain"]
  },
},
```
and entity attributes and mapping config, but I'm not sure how we reference it or ensure aligned in creating response. We just want to add the userID as an attribute...

```json
  "name_id_format": [NAMEID_FORMAT_TRANSIENT, NAMEID_FORMAT_PERSISTENT],
  "allow_unknown_attributes": True,
  "entity_attributes": [
    {
      "name_format": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
      "name": "urn:oasis:names:tc:SAML:profiles:subject-id:req",
      # "friendly_name" is not set
      "values": ["any"],
    },
  ]
},
},
"debug": 1,
 "attribute_map_dir": "./app/python_api/resolvers/saml-soo-attribute-maps",
```
and we have mapping file...though its confusing if we configure directory does it look for all files in that?

```py
MAP = {
  "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
  "fro": {
    'urn:mace:dir:attribute-def:userid': 'userid',
  },
  "to": {
    'userid':'urn:mace:dir:attribute-def:userid' ,
  }
}
```

**Comment by c00kiemon5ter** [comment]
Hello @bjm88,

the user attributes are passed in through the `identity` parameter. The `identity` is a dictionary of friendly-names to attribute-values.

You want to have an `Attribute` element with `FriendlyName="userId"` (ok) and `Name="userId"` (which is not standard)
and `NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"`. Since this is a non-standard attribute it should be created with the help of attribute maps.

---

Once you set `attribute_map_dir` you are bypassing the internal maps that pysaml2 knows about. So, you should redefine all attributes you want/need in that file. The primary element in a mapping is the identifier, which corresponds to the `NameFormat`. 

Here we will define a single mapping. This means that no other attribute will be recognized:
```py
MAP = {
  "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified",
  "fro": {
    "userId": "userId",
  },
  "to": {
    "userId": "userId",
  }
}
```

Compared to what you posted on the question
- the identifier has changed to match the `NameFormat` xml-attribute value (unspecified instead of basic).
- the mapping between the FriendlyName and Name is as you showed on the example `Attribute` element; both attributes had the value `userId` - not a `urn:...` identifier. 

(If you intended to get something different change these as needed.)

---

As I said in the beginning, the user attributes are passed in through the `identity` parameter. The `identity` is a dictionary of friendly-names to attribute-values. So, ensure `identity contains the value you need:

```py
identity["userId"] = identity["mrn"]
_resp = IDP.create_authn_response(identity, in_response_to, destination, sp_entity_id, userid=identity["mrn"], binding=BINDING_HTTP_POST, name_id=name_id, authn=auth_info)
```

Here, we map the friendly-name `userId` to have the value of `identity["mrn"]`. 
Without this, the value is mapped to a friendly-name `mrn`, which we have not defined.


Please, try those changes and let me know.

**Comment by bjm88** [comment]
thank you @c00kiemon5ter !!  Really helps understand the different options.  Our intent was not to go non-standard if we dont have to.  We want to pass the NameFormat( ?) or user ID or subject, not sure the standard SAML term for the main user identifier, but we just want to ensure that is included and know how to add extras.  Will give this a try, but not so clear on this part in the code
name_id = IDP.ident.get_nameid(identity["patientId"], name_id_policy, sp_name_qualifier, name_qualifier)
.  Would be great to see an example of a standard way to pass a users ID and also add a secondary attribute that is non standard.  Will try to mixin of ADF_V20_Map to start.

**Comment by c00kiemon5ter** [comment]
A SAML `Response` contains an `<Assertion>` with `<Attribute>`s about a subject, and at the same time defines a separate structure to _identify_ the subject - namely, the `<Subject><NameID>` element. The `NameID` is not an `Attribute`, but a separate node. The `Attribute`s may contain the same information as the `NameID`, but traditionally the subject was identified by the `NameID` and additional information would reside in the `<Attribute>`s.

So, the `identity` param will be converted to `<Attribute>`s, while the `userid` param will be converted to `<Subject><NameID>`.

---

I just noticed you're using both `userid` and `name_id`. If `name_id` is set, `userid` is not used. The `name_id` param is expected to be a `saml2.saml.NameID` object, while the `userid` param is the value (a `str`) that will be used to create such an object internally. You do not need both. I would probably use `name_id` to have more control over how that object looks like.

```py
from saml2.saml import NAMEID_FORMAT_PERSISTENT
from saml2.saml import NameID


name_id = NameID(
  text=identity["patientId"],
  format=NAMEID_FORMAT_PERSISTENT,
)

_resp = IDP.create_authn_response(
  identity,
  in_response_to,
  destination,
  sp_entity_id,
  binding=BINDING_HTTP_POST,
  name_id=name_id,
  authn=auth_info,
)
```

**Comment by bjm88** [comment]
Thanks again @c00kiemon5ter , makes sense on user_id vs name_id.  If we comment out the mapping we are seeing expected results and if we also dont use a policy in our settings.  I think the confusing thing was we had conflicting or too much config from trying to reference off different examples out there on the internet and combine them.

Like when would we need this ?
#"entity_attributes": [
                #    {
                #        "name_format": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
                #        "name": "urn:oasis:names:tc:SAML:profiles:subject-id:req",
                #        # "friendly_name" is not set
                #        "values": ["any"],
                #    },

We commented this out and then just added this config in IDP settings
"allow_unknown_attributes": True,

and it now puts all the Attributes for our identity map as expected.  I think we are all set, hopefully this helps others, thanks!

**Comment by c00kiemon5ter** [comment]
Great!

Regarding `entity_attributes`, the snippet you show in the message above would add an `<EntityAttributes><saml:Attribute>` element in the metadata document. It would signify that the entity (in this case it should be an SP) described with that metadata document, requests from the IdP a [`subject-id`](https://docs.oasis-open.org/security/saml-subject-id-attr/v1.0/cs01/saml-subject-id-attr-v1.0-cs01.html) attribute of any type (`subject-id` or `pairwise-id`).

**Comment by c00kiemon5ter** [comment]
I will close this now, but if you need anything else, feel free to reply here or create a new issue.

Thanks!
