### ISSUE TITLE
EntityDescriptor vs EntitiesDescriptor for IDP and SP metadata, how to control root node?

### ISSUE THREAD

**Issue by bjm88** [IdentityPython/pysaml2#848]
Hi - we have requirements to have our root node for IDP be `EntityDescriptor` vs the multiple listing container `EntitiesDescriptor` node that seems to be the default for pysaml2.

We also need to allow framework to expect and process an SP that has `EntityDescriptor` as their root in metadata.

How can we control this? Can't find anything in documentation, thanks.

**Comment by bjm88** [comment]
Found this
'node_name': 'urn:oasis:names:tc:SAML:2.0:metadata:EntityDescriptor'}]
that can be added to the SP config in
"metadata": {
            "remote": [
                { "url": '..."
 'node_name': "..."

Wondering does it work for the metadata being hosted. as an IDP not just consuming SP ?

**Comment by c00kiemon5ter** [comment]
This issue is related to https://github.com/IdentityPython/pysaml2/issues/845

---

@bjm88 the `node_name` option should work for both SPs and IdPs using the `remote` metadata source. Try it out and let us know.

**Comment by c00kiemon5ter** [comment]
hm, maybe what you're asking is something different..
If you want to control the root node name for the metadata that the library produces the answer is no. The `node_name` option will define the expected root node of the metadata document that will be fetched.

**Comment by bjm88** [comment]
thanks @c00kiemon5ter.  We are asking both.  So for consuming the SP metadata this solves the issue.
How do we control what is generated to be  "EntityDescriptor" as the root also vs EntitiesDescriptor ?  Does that just happen naturally.  We actually see our IDP metadata generated from this library is EntityDecriptor but if we needed to change in future we were not sure how.

**Comment by c00kiemon5ter** [comment]
> How do we control what is generated to be "EntityDescriptor" as the root also vs EntitiesDescriptor?

You cannot do that. The entity is a single thing and returns one `EntityDescriptor` to describe itself. `EntitiesDescriptor` would be returned if the document described multiple entities.

Having said this, it is very common to post-process the metadata document, especially when they are going to be advertise by a federation that enforces some common policies across multiple entities.

**Comment by bjm88** [comment]
Ok thanks @c00kiemon5ter .  We can close this, hopefully helps others from google search on this topic.  Happy holidays and appreciate the continued support of this repo!
