### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by ryanbutterfield** [IdentityPython/pysaml2#853]
Hi,

We maintain a Python 2.7 project. It uses PySAML2 for authentication for enterprise clients. We were surprised due to the security-sensitive nature of this library that Python 2.7 support was dropped some releases ago. 

We understand that Python 2.7 is no longer supported, but a lot of Python 2.7 projects still are..

So, we took the latest 7.1.0 code and ported it back to Python 2.7. Suprisingly there were very few changes required. The majority of changes were people writing code in Python 3 only syntax, which provided marginal benefits to readibility.

Regardless, our fork can be found at (https://github.com/masterapps-au/pysaml2). It passes all py tests and we are using it in production. Please feel free to merge back in the changes (I know this is highly unlikely), or provide a link to our port for other users like us.

Thanks for a great library.

## Code Version
7.1.0

## Expected Behavior
Library works on Python 2.7 like it used to

## Current Behavior
Only works on Python 3.6+

## Possible Solution
Re-introduce support for Python 2.7, or link to Python 2.7 fork

## Steps to Reproduce
Install in Python 2.7 environment

**Comment by c00kiemon5ter** [comment]
Hello and thanks for getting in contact.

We have decided to move forward and away from python2. Right now the changes are indeed small, but there are future plans for a bigger refactoring of the codebase and introduction of typing annotations.

Having said this, if you agree, I can add a pointer to your fork to make it easier for people to find it in one of our docs/pages.

I will close the issue now, but do let me know if that is ok with you. Probably with a text like the following:

> PySAML2 has dropped support for Python2 on version X. A fork of PySAML2 with support for Python2 is maintained at <link-to-repo>. IdentityPython is not associated with that effort and cannot guarantee feature compatibility or back-porting of important changes.

**Comment by ryanbutterfield** [comment]
Hi Ivan. No problem. Yes a link to our fork would be good to help others like us. Thanks.

**Comment by c00kiemon5ter** [comment]
done by 92445ac5

**Comment by ryanbutterfield** [comment]
Hi Ivan/Team. We no longer maintain or use this fork. Please remove the link to it.
