### ISSUE TITLE
Metadata string (create_metadata_string) uses always default algorithms

### ISSUE THREAD

**Issue by savijoki** [IdentityPython/pysaml2#865]
Generating metadata string (`create_metadata_string`) doesn't allow to specify signing and digest algorithms. This results that the default algorithm (`ds.DefaultSignature().get_digest_alg()`) is always used in the metadata string (in my case `http://www.w3.org/2000/09/xmldsig#sha1`).

## Code Version

7.1.2

## Expected Behavior

There should be a possibility to define the desired algorithm for signing and digests, preferably so that the algorithms are retrieved from the `Config`-instance.  

## Current Behavior

Metadata string always uses default algorithms if `sign=True` instead of using the algorithms used for initializing the `Config`-instance. `sign_entity_descriptor`-funktion has default values of `None` for algorithms and since these aren't passed from `create_metadata_string`, these are always `None` and thus in `pre_signature_part`-function always uses the default algorithms (`digest_alg = ds.DefaultSignature().get_digest_alg()`).

## Possible Solution

When creating the metadata string config algorithms should be passed to `sign_entity_descriptor`:

`eid, xmldoc = sign_entity_descriptor(eid, mid, secc, config.signing_algorithm, config.digest_algorithm)` 

## Steps to Reproduce

1. Create `Config` instance with with other algorithm than the default (e.g. `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`)
2. Create metadata string for that instance (`sign=True`)
3. Metadata string contains the default algorithm (e.g. `http://www.w3.org/2000/09/xmldsig#sha1`) instead of the desired one

**Comment by c00kiemon5ter** [comment]
Hello @savijoki,

this is a limitation at this point and we have plans to fix this along with the ability to specify the supported algos to be used when exchanging saml messages.

**Comment by savijoki** [comment]
@c00kiemon5ter Thank you for clarification. Just to be clear this is only a limitation in creating the metadata string? Or does this limit the encryption algorithms that can be used with pysaml2 at this time?

**Comment by c00kiemon5ter** [comment]
This is only on the metadata signing operation. Signing and verifying SAML messages with different algos is supported (roughly {dsa,rsa,ecdsa}-{sha1,sha224,sha256,sha384,sha512,ripemd160})

**Comment by c00kiemon5ter** [comment]
I've pushed e16beb6fdf84d6596d0cc01b0b41ca25b47c6fe9 to allow the proper arguments to propagate. This should allow you to pass in the algos directly, otherwise fallback to the values set within the config object.

Let me know this change solves your issue.
