### ISSUE TITLE
[question] How to retrieve assertion attributes?

### ISSUE THREAD

**Issue by nkov** [IdentityPython/pysaml2#867]
## Code Version
6.1.0

## Summary
I have a parsed AuthnResponse, that I've obtained using:
```python
authn_response = Saml2Client(config=config).parse_authn_request_response(saml_response, entity.BINDING_HTTP_POST)
```
I can get the subject via:
```python
subject = authn_response.get_subject().text.lower()
```

But I don't see documentation about how to get the attributes, eg in the XML:
```xml
<saml2:AttributeStatement>
    <saml2:Attribute Name="first_name">
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">Nick</saml2:AttributeValue>
    </saml2:Attribute>
    <saml2:Attribute Name="last_name">
        <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">Test</saml2:AttributeValue>
    </saml2:Attribute>
</saml2:AttributeStatement>
```

Should I parse these from XML directly or is there a proper method for getting the values for provided attributes `first_name` and `last_name`?

**Comment by c00kiemon5ter** [comment]
Hello, accessing `authn_response.ava` should get you the attributes as a mapping of friendly-name to list of values.

You can also get the values by following the xml structure:

```python
print(authn_response.assertion.subject.name_id.text)
print(authn_response.assertion.attribute_statement[0].attribute[0].name)
print(authn_response.assertion.attribute_statement[0].attribute[0].friendly_name)
print(authn_response.assertion.attribute_statement[0].attribute[0].attribute_value[0].text)
```

**Comment by nkov** [comment]
Thanks @c00kiemon5ter, the second approach worked but `auth_response.ava` gives me an empty dictionary. Is there somewhere I need to specify these attributes as existing?

**Comment by c00kiemon5ter** [comment]
Yes; you need to specify appropriate mappings like the builtins under https://github.com/IdentityPython/pysaml2/tree/master/src/saml2/attributemaps

See more about the relevant configuration `attribute_map_dir` and the format of those files here: https://pysaml2.readthedocs.io/en/latest/howto/config.html#attribute-map-dir

---

In your case, no `NameFormat` attribute is specified on the `Attribute` element. This means that the default identifier `urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified` is used. So, your mapping file would look like

```python
from pysaml2.attributemaps.adfs_v20 import MAP as ADFS_v20_MAP

MAP = {
  "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified",
  "fro": {
    **ADFS_v20_MAP["fro"],
    "first_name": "first_name",
    "last_name": "last_name",
  },
  "to": {
    **ADFS_v20_MAP["to"],
    "first_name": "first_name",
    "last_name": "last_name",
  }
}
```

or, if you don't care about other attributes, just:

```python
MAP = {
  "identifier": "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified",
  "fro": {
    "first_name": "first_name",
    "last_name": "last_name",
  },
  "to": {
    "first_name": "first_name",
    "last_name": "last_name",
  }
}
```
