### ISSUE TITLE
Support pymongo 4.X

### ISSUE THREAD

**Issue by opoplawski** [IdentityPython/pysaml2#868]
Looks like motor should now support pymongo 4.X with the release of 3.0.0.  It would be nice if pysaml2 could support it so we could update pymongo in Fedora.  See also #843

**Comment by c00kiemon5ter** [comment]
Fixed by 37d92b3

**Comment by kyrias** [comment]
Any idea of when a new release with the fix will be made?  The commit that fixes the API usage sadly doesn't apply on the latest release.

**Comment by c00kiemon5ter** [comment]
Hello, I will be making new releases within this week.
