### ISSUE TITLE
Need to remove the host dependency of xmlsec1 when using a conda installation

### ISSUE THREAD

**Issue by nilupulmanodya** [IdentityPython/pysaml2#913]
I need your help. We want to remove the host dependency of xmlsec1 when using a conda installation. I assume that we can also use the conda package libxmlsec1, which is also available as a Debian package. We would prefer to use the conda package because it is not a host requirement when we can add it to the environment. Is this an alternative to the xmlsec1 mentioned in the [README?](https://github.com/IdentityPython/pysaml2#readme)

### Code Version

7.4.2

**Comment by c00kiemon5ter** [comment]
Does the conda `libxmlsec1` package provide an executable? If yes, then this should be doable.

You would have to set the right path to the binary by setting the [`xmlsec_binary` config option](https://pysaml2.readthedocs.io/en/latest/howto/config.html#xmlsec-binary)
