### ISSUE TITLE
Allow marking `ContactPerson` as `remd:contactType="http://refeds.org/metadata/contactType/security"`

### ISSUE THREAD

**Issue by max-moser** [IdentityPython/pysaml2#956]
AFAIK, marking contact persons as "security" requires using an attribute from a REFEDS extension.
Examples of such `<ContactPerson>` elements can be found in [tests/remote_data/InCommon-metadata-export.xml](https://github.com/IdentityPython/pysaml2/blob/master/tests/remote_data/InCommon-metadata-export.xml):
```xml
<ContactPerson xmlns:remd="http://refeds.org/metadata" contactType="other" remd:contactType="http://refeds.org/metadata/contactType/security">
  <GivenName>Shibboleth Contact</GivenName>
  <EmailAddress>contact@shibboleth.net</EmailAddress>
</ContactPerson>
```

As far as I could see in the code, only the "base" `contactType` is taken into account when exporting metadata [right now](https://github.com/IdentityPython/pysaml2/blob/3daa066703f5ec433aeb9714a847330c540fc5d4/src/saml2/md.py#L732).

It would be cool if there were a possibility to create the REFEDS extension attribute on export as well.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @max-moser ,

I have this working with SATOSA - using only functionality available in pysaml2 for exporting the metadata.

See the examples contributed in https://github.com/IdentityPython/SATOSA/pull/430.

The key bit is that pysaml2 supports `extension_attributes` for ContactPerson - and you can pass the `remd:ContactType` (alongside the XML namespace declaration) this way.

Hope this helps.

Cheers,
Vlad

**Comment by max-moser** [comment]
Hey @vladimir-mencl-eresearch ,

Thanks a ton, this is _exactly_ what I needed, works like a charm!

Cheers,
Max
